### ISSUE TITLE
debug运行没有问题,混淆出错,不知错在何处

### ISSUE THREAD

**Issue by huyuxin95** [LitePalFramework/LitePal#120]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100, result=-1, data=Intent { (has extras) }} to activity {com.jju.yuxin.cinews/com.jju.yuxin.cinews.activity.MainActivity}: org.litepal.exceptions.DatabaseGenerateException: can not find a class named com.jju.yuxin.cinews.db.Favors
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3607)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3650)
	at android.app.ActivityThread.access$1400(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1370)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: org.litepal.exceptions.DatabaseGenerateException: can not find a class named com.jju.yuxin.cinews.db.Favors
	at org.litepal.LitePalBase.getSupportedFields(Unknown Source)
	at org.litepal.LitePalBase.getTableModel(Unknown Source)
	at org.litepal.tablemanager.Generator.getAllTableModels(Unknown Source)
	at org.litepal.tablemanager.Creator.createOrUpgradeTable(Unknown Source)
	at org.litepal.tablemanager.Generator.create(Unknown Source)
	at org.litepal.tablemanager.Generator.create(Unknown Source)
	at org.litepal.tablemanager.LitePalOpenHelper.onCreate(Unknown Source)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at org.litepal.tablemanager.Connector.getWritableDatabase(Unknown Source)
	at org.litepal.tablemanager.Connector.getDatabase(Unknown Source)
	at org.litepal.crud.DataSupport.deleteAll(Unknown Source)
	at com.jju.yuxin.cinews.b.a.a(Unknown Source)
	at com.jju.yuxin.cinews.activity.MainActivity.onActivityResult(Unknown Source)
	at android.app.Activity.dispatchActivityResult(Activity.java:6192)
	at android.app.ActivityGroup.dispatchActivityResult(ActivityGroup.java:126)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3603)
	... 10 more
org.litepal.exceptions.DatabaseGenerateException: can not find a class named com.jju.yuxin.cinews.db.Favors
	at org.litepal.LitePalBase.getSupportedFields(Unknown Source)
	at org.litepal.LitePalBase.getTableModel(Unknown Source)
	at org.litepal.tablemanager.Generator.getAllTableModels(Unknown Source)
	at org.litepal.tablemanager.Creator.createOrUpgradeTable(Unknown Source)
	at org.litepal.tablemanager.Generator.create(Unknown Source)
	at org.litepal.tablemanager.Generator.create(Unknown Source)
	at org.litepal.tablemanager.LitePalOpenHelper.onCreate(Unknown Source)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at org.litepal.tablemanager.Connector.getWritableDatabase(Unknown Source)
	at org.litepal.tablemanager.Connector.getDatabase(Unknown Source)
	at org.litepal.crud.DataSupport.deleteAll(Unknown Source)
	at com.jju.yuxin.cinews.b.a.a(Unknown Source)
	at com.jju.yuxin.cinews.activity.MainActivity.onActivityResult(Unknown Source)
	at android.app.Activity.dispatchActivityResult(Activity.java:6192)
	at android.app.ActivityGroup.dispatchActivityResult(ActivityGroup.java:126)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3603)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3650)
	at android.app.ActivityThread.access$1400(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1370)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by guolindev** [comment]
混淆配置这样写就可以了：

-keep class org.litepal.** {
*;
}

-keep class * extends org.litepal.crud.DataSupport {
*;
}
