### ISSUE TITLE
String 类型的List作为一个成员变量保存，保存成功后取对象时报空指针

### ISSUE THREAD

**Issue by coder-luhao** [LitePalFramework/LitePal#140]
Album对象里面有一个` List<String>`以及其他字段，保存的时候提示保存成功，取数据的时候Album报空指针。哪里可能出错了呢？给一些建议吧～

异常：
`
Caused by: java.lang.NullPointerException
                                                                  at org.litepal.crud.DataHandler.setToModelByReflection(DataHandler.java:1341)
                                                                  at org.litepal.crud.DataHandler.setGenericValueToModel(DataHandler.java:787)
                                                                  at org.litepal.crud.DataHandler.query(DataHandler.java:139)
                                                                  at org.litepal.crud.QueryHandler.onFindLast(QueryHandler.java:97) 
                                                                  at org.litepal.crud.DataSupport.findLast(DataSupport.java:576) 
                                                                  at org.litepal.crud.DataSupport.findLast(DataSupport.java:561) 
`
`
aused by: org.litepal.exceptions.DataSupportException
                                                                  at org.litepal.crud.DataHandler.query(DataHandler.java:150)
                                                                  at org.litepal.crud.QueryHandler.onFindLast(QueryHandler.java:97)
                                                                  at org.litepal.crud.DataSupport.findLast(DataSupport.java:576)
                                                                  at org.litepal.crud.DataSupport.findLast(DataSupport.java:561)
`
空指针异常代码：
`Album album = DataSupport.findLast(Album.class);`
Album类代码：
`public class DraftBean extends DataSupport implements Parcelable {
    private int album Id; 
    private List<String> title;
}
`

**Comment by guolindev** [comment]
空指针报在DataHandler的1341行，我看了一下那行的代码，是在向集合里面进行add值，这里会出现空指针，除非是你的实体类里面集合是null，也就是你的集合字段还没有初始化。

虽然你没有把实体类的代码贴出来，但我猜测问题应该是就在这里了。你说添加了一个List<String>字段对吧，你是不是没有对它进行实例化呢？

**Comment by coder-luhao** [comment]
由于我没有在Mondel里面初始化集合的习惯，并且已初始化的集合传入Mondel无需对Mondel中的集合变量初始化的原因造成了这个问题。都怪我没仔细阅读Quick Setup，遇到这种问题也是当局者迷，感谢🙏 @guolindev 指出问题的所在，十分感谢！
