### ISSUE TITLE
启动直接空指针了

### ISSUE THREAD

**Issue by lixuejiao329** [LitePalFramework/LitePal#142]
启动直接空指针了，怎么回事。
这是配置文件
<?xml version="1.0" encoding="utf-8" ?>
<litepal>
    <dbname value="demo"></dbname>
    <version value="1"></version>
    <list>
        <mapping name = "***.User"></mapping>
    </list>
</litepal>
然后再application当中初始化，
然后再主界面调用  Connector.getDatabase() 就直接报空指针异常了。

**Comment by gundumw100** [comment]
这个我估计是你用错了，不会出现这么低级的错误吧

**Comment by guolindev** [comment]
应该是你的用法出错了，可以把错误日志还有你的用法贴出来，要不然也没办法定位。

**Comment by lixuejiao329** [comment]
配置文件
`<litepal>
    <dbname value="lite_demo" ></dbname>
    <version value="1" ></version>
    <list>
        <mapping name = "com.xf9h.app.model.User"></mapping>
    </list>
</litepal>`
application初始化的代码：
`
    @Override
    public void onCreate() {
        super.onCreate();
        LitePal.initialize(this);
    }`
 使用的代码：
`
        Connector.getDatabase();
        User user = new User();
        user.setUserId(1);
        user.setUserName("张三");
        user.setPhone("15500000000");
        user.save();`
User对象：
`public class User extends DataSupport{

    private int userId;
    private String userName;
    private String phone;

  /**get set*/
}`

**Comment by lixuejiao329** [comment]
这个是错误代码：
` Caused by: java.lang.NullPointerException
                                                                  at java.lang.Class.classForName(Native Method)
                                                                  at java.lang.Class.forName(Class.java:324)
                                                                  at java.lang.Class.forName(Class.java:285)
                                                                  at org.litepal.LitePalBase.getSupportedFields(LitePalBase.java:194)
                                                                  at org.litepal.LitePalBase.getTableModel(LitePalBase.java:123)
                                                                  at org.litepal.tablemanager.Generator.getAllTableModels(Generator.java:72)
                                                                  at org.litepal.tablemanager.Creator.createOrUpgradeTable(Creator.java:45)
                                                                  at org.litepal.tablemanager.Generator.create(Generator.java:167)
                                                                  at org.litepal.tablemanager.Generator.create(Generator.java:205)
                                                                  at org.litepal.tablemanager.LitePalOpenHelper.onCreate(LitePalOpenHelper.java:83)
                                                                  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:267)
                                                                  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:175)
                                                                  at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:58)
                                                                  at org.litepal.tablemanager.Connector.getDatabase(Connector.java:81)
                                                                  at com.xf9h.app.MainActivity.onCreate(MainActivity.java:33)
                                                                  at android.app.Activity.performCreate(Activity.java:6372)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539) 
                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:168) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                  at android.os.Looper.loop(Looper.java:150) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5665) 
                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712) `

**Comment by lixuejiao329** [comment]
我大概发现问题在哪里了，但是不知道什么原因。就是配置文件，我自己创建的配置文件不行，但是从demo当中把配置文件复制过来用就可以。但是我创建的，跟复制来的两个文件，文件名跟内容是一模一样的。

**Comment by guolindev** [comment]
也许是文件类型不对吧，不知道具体你是怎么创建的，那你就用复制过来的文件好了，这个没关系的。

**Comment by iris48** [comment]
你好  我想问问 Connector.getDatabase(); 这句话是写在哪里的 每次数据库操作都要使用吗

**Comment by iris48** [comment]
作为小白 这一个litepal真的要搞死我了
