### ISSUE TITLE
使用 LitePal 1.4.1 版本创建数据库报错

### ISSUE THREAD

**Issue by DysaniazzZ** [LitePalFramework/LitePal#148]
Rt，使用LitePal 1.4.1 版本创建数据库时报错，提示数据库名为空或未定义：

```
org.litepal.exceptions.InvalidAttributesException: dbname is empty or not defined in litepal.xml file
    at org.litepal.parser.LitePalAttr.checkSelfValid(LitePalAttr.java:191)
    at org.litepal.tablemanager.Connector.buildConnection(Connector.java:99)
    at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:57)
    at org.litepal.tablemanager.Connector.getDatabase(Connector.java:81)
    at org.litepal.LitePal.getDatabase(LitePal.java:62)
    at com.example.dysaniazzz.chapter06.LitePalUsageActivity.onClick(LitePalUsageActivity.java:42)
    at com.example.dysaniazzz.chapter06.LitePalUsageActivity_ViewBinding$1.doClick(LitePalUsageActivity_ViewBinding.java:37)
    at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
    at android.view.View.performClick(View.java:4909)
    at android.view.View$PerformClick.run(View.java:20390)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5826)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1009)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
```

然而我已经在assets/litepal.xml中定义了 `dbname`：

```
<?xml version="1.0" encoding="utf-8"?>
<litepal>

    <dbname value="LitePalDemo"/>
    <version value="1"/>
    <list>
        <mapping class="com.example.dysaniazzz.bean.AlbumModel"></mapping>
        <mapping class="com.example.dysaniazzz.bean.SongModel"></mapping>
    </list>

</litepal>
```

在自定义的Application中的初始化语句为：
`LitePal.initialize(mContext);`

在代码中创建的语句为：
`LitePal.getDatabase();`

**Comment by guolindev** [comment]
这个错误提示的可能有点问题，下个版本会优化一下。

你遇到的实际问题应该是litepal.xml不存在，因为从1.4.0版本开始支持多数据库，允许不使用litepal.xml了，因此LitePal检测到没有litepal.xml文件并不会立即报错。但是你并没有使用多数据库功能，还是使用的传统的数据库配置，这个时候LitePal会对检查配置项的内容，发现dbname不存在，就报了上面的错误，而实际的错误应该是litepal.xml文件不存在。

你说你配置了litepal.xml文件，我估计应该是路径的位置配置错了，才导致无法找到。建议你可以去参考一下sample中的配置路径，然后修改一下你的代码就可以解决了。

**Comment by DysaniazzZ** [comment]
果然是，我把assets目录直接放在src目录下了(捂脸。。。谢谢郭神

**Comment by hestyle** [comment]
我的也是报这个dbname找不到的问题
![image](https://user-images.githubusercontent.com/44233477/95699378-ddb17180-0c76-11eb-8465-98c13e823ecc.png)
