### ISSUE TITLE
支持集合数据储存的Bean不初始化集合字段就会报错

### ISSUE THREAD

**Issue by ningxz** [LitePalFramework/LitePal#152]
听说litepal支持集合数据存储， 马上更新了最新版本， 但是一直报以下这个错误，  跟了源码不知道为什么这里为什么会有null值， 这里到底是colleciton的值为null， 还是 value的值为null呢？ 调试打印不出这两个变量的值
```java
Collection<Object> collection = (Collection<Object>) DynamicExecutor.getField(modelInstance, field.getName(), modelInstance.getClass());    //DataHanler 1340行
collection.add(value);  // 1341行
```

将相应bean里关于集合的字段 先初始化 这个错误就不出现了
比如 private List<String> imagePath   ---->  List<String> imagePath = new ArrayList<>();

```java
FATAL EXCEPTION: UploadFileService
E/AndroidRuntime( 2789): Process: com.meizu.feedback, PID: 2789
E/AndroidRuntime( 2789): org.litepal.exceptions.DataSupportException: Attempt to invoke interface method 'boolean java.util.Collection.add(java.lang.Object)' on a null object reference
E/AndroidRuntime( 2789): 	at org.litepal.crud.DataHandler.query(SourceFile:150)
E/AndroidRuntime( 2789): 	at org.litepal.crud.QueryHandler.onFindFirst(SourceFile:78)
E/AndroidRuntime( 2789): 	at org.litepal.crud.DataSupport.findFirst(SourceFile:542)
E/AndroidRuntime( 2789): 	at org.litepal.crud.DataSupport.findFirst(SourceFile:527)
E/AndroidRuntime( 2789): 	at com.ningxz.feedback.service.UploadFileService.a(SourceFile:135)
E/AndroidRuntime( 2789): 	at com.ningxz.feedback.service.UploadFileService$1.run(SourceFile:88)
E/AndroidRuntime( 2789): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 2789): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 2789): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 2789): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/AndroidRuntime( 2789): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Collection.add(java.lang.Object)' on a null object reference
E/AndroidRuntime( 2789): 	at org.litepal.crud.DataHandler.setToModelByReflection(SourceFile:1341)
E/AndroidRuntime( 2789): 	at org.litepal.crud.DataHandler.setGenericValueToModel(SourceFile:787)
E/AndroidRuntime( 2789): 	at org.litepal.crud.DataHandler.query(SourceFile:139)
E/AndroidRuntime( 2789): 	... 9 more
```

**Comment by FelixZ88** [comment]
我也遇到了同样的问题。

**Comment by guolindev** [comment]
这是一个bug，现在已经修复掉了，具体代码可以查看这条commit https://github.com/LitePalFramework/LitePal/commit/a24f925eff5b27392d79660d4a26569a4161ac79
