### ISSUE TITLE
为什么查询数据时会崩溃？

### ISSUE THREAD

**Issue by chlseeky** [LitePalFramework/LitePal#175]
E/SQLiteLog: (1802) statement aborts at 30: [SELECT * FROM stocksimpleinfo ORDER BY id] disk I/O error
E/SQLiteQuery: exception: disk I/O error (code 1802); query: SELECT * FROM stocksimpleinfo ORDER BY id
 E/AVUncaughtExceptionHandler: AVUncaughtExceptionHandler caught a DataSupportException exception 
E/Parcel: Reading a NULL string not supported here.
E/CrashHandler: In thread: Thread[Thread-58124,5,main]
                                                                         UncaughtException detected: org.litepal.exceptions.DataSupportException: disk I/O error (code 1802)
                                                                             at org.litepal.crud.DataHandler.query(DataHandler.java:151)
                                                                             at org.litepal.crud.QueryHandler.onFindAll(QueryHandler.java:123)
                                                                             at org.litepal.crud.DataSupport.findAll(DataSupport.java:1018)
                                                                             at org.litepal.crud.DataSupport$9.run(DataSupport.java:1038)
                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                          Caused by: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
                                                                             at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
                                                                             at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
                                                                             at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
                                                                             at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                                             at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
                                                                             at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
                                                                             at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
                                                                             at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
                                                                             at org.litepal.crud.DataHandler.query(DataHandler.java:132)
                                                                             at org.litepal.crud.QueryHandler.onFindAll(QueryHandler.java:123) 
                                                                             at org.litepal.crud.DataSupport.findAll(DataSupport.java:1018) 
                                                                             at org.litepal.crud.DataSupport$9.run(DataSupport.java:1038) 
                                                                             at java.lang.Thread.run(Thread.java:818)

**Comment by joleyii** [comment]
我这里也出现了Exception org.litepal.exceptions.DataSupportException: disk I/O error 的问题 为什么要关掉这个问题

**Comment by csbz17027** [comment]
同出现这个问题，代码无法追溯，有人知道问题的原因吗？
