### ISSUE TITLE
DataSupportException

### ISSUE THREAD

**Issue by LloydFinch** [LitePalFramework/LitePal#186]
When I use it in more than one thread, it will like this:
org.litepal.exceptions.DataSupportException: attempt to re-open an already-closed objec

Please tell me how can I solve it

**Comment by guolindev** [comment]
anything more details? an error stack trace will be helpful.

**Comment by LloydFinch** [comment]
org.litepal.exceptions.DataSupportException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.gzkj.eye.eyenurse/databases/eYe_data_1741.db
	at org.litepal.crud.DataHandler.query(DataHandler.java:150)
	at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
	at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:212)
	at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:188)
	at com.gzkj.eye.eyenurse.manager.TimeZoneManager.getEyeTimeZones(TimeZoneManager.java:186)
	at com.gzkj.eye.eyenurse.manager.TimeZoneManager.getDeviceInUseTimeZones(TimeZoneManager.java:179)
	at com.gzkj.eye.eyenurse.manager.DataAnalyer.getEyeUseTimeReal(DataAnalyer.java:79)
	at com.gzkj.eye.eyenurse.manager.DataAnalyer.getEyeUseTime(DataAnalyer.java:99)
	at com.gzkj.eye.eyenurse.model.DataModel.(DataModel.java:20)
	at com.gzkj.eye.eyenurse.ui.activity.LocalIndexActivity.-com_gzkj_eye_eyenurse_ui_activity_LocalIndexActivity_lambda$4(LocalIndexActivity.java:521)
	at com.gzkj.eye.eyenurse.ui.activity.LocalIndexActivity$-void__init___LambdaImpl1.run(LocalIndexActivity.java)
	at java.lang.Thread.run(Thread.java:841)

**Comment by LloydFinch** [comment]
org.litepal.exceptions.DataSupportException: The hasUpload field in DataSupport class is necessary which does not exist.
	at org.litepal.crud.DataHandler.query(DataHandler.java:151)
	at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
	at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:232)
	at org.litepal.crud.ClusterQuery.findFirst(ClusterQuery.java:312)
	at org.litepal.crud.ClusterQuery.findFirst(ClusterQuery.java:284)
	at com.gzkj.eye.eyenurse.manager.TimeZoneManager.getLastTimeZone(Unknown Source)
	at com.gzkj.eye.eyenurse.manager.DataCollector.startIfNeed(Unknown Source)
	at com.gzkj.eye.eyenurse.service.ScreenTimerService$1.run(Unknown Source)
	at java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by guolindev** [comment]
I guess you have instantiated multiple instances of SQLiteDatabase and you called db.close() more than the instances you created.  Actually you don't need to call db.close() at all. LitePal will handle that for you.

And the second exception, indicates that hasUpload field does not exist. I am guessing this field is added by you after database created and you didn't increase the version number.

**Comment by LloydFinch** [comment]
you are right, I see,thank you
