### ISSUE TITLE
无法创建数据库

### ISSUE THREAD

**Issue by imurluck** [LitePalFramework/LitePal#196]
04-22 06:37:29.089 1996-1996/? E/memtrack: Couldn't load memtrack module (No such file or directory)
04-22 06:37:29.089 1996-1996/? E/android.os.Debug: failed to load memtrack module: -2
04-22 06:37:30.841 2048-2048/? E/memtrack: Couldn't load memtrack module (No such file or directory)
04-22 06:37:30.841 2048-2048/? E/android.os.Debug: failed to load memtrack module: -2
04-22 06:37:43.387 2061-2061/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.litepaldatabase, PID: 2061
                                                 java.lang.NumberFormatException: Invalid int: "1.0"
                                                     at java.lang.Integer.invalidInt(Integer.java:138)
                                                     at java.lang.Integer.parse(Integer.java:410)
                                                     at java.lang.Integer.parseInt(Integer.java:367)
                                                     at java.lang.Integer.parseInt(Integer.java:334)
                                                     at org.litepal.parser.LitePalParser.usePullParse(LitePalParser.java:160)
                                                     at org.litepal.parser.LitePalParser.parseLitePalConfiguration(LitePalParser.java:102)
                                                     at org.litepal.parser.LitePalAttr.getInstance(LitePalAttr.java:91)
                                                     at org.litepal.tablemanager.Connector.buildConnection(Connector.java:98)
                                                     at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:57)
                                                     at org.litepal.tablemanager.Connector.getDatabase(Connector.java:81)
                                                     at org.litepal.LitePal.getDatabase(LitePal.java:62)
                                                     at com.example.litepaldatabase.MainActivity$1.onClick(MainActivity.java:20)
                                                     at android.view.View.performClick(View.java:4780)
                                                     at android.view.View$PerformClick.run(View.java:19866)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
04-22 06:37:43.428 795-795/? E/EGL_emulation: tid 795: eglCreateSyncKHR(1209): error 0x3004 (EGL_BAD_ATTRIBUTE)

老哥，这种情况咋整啊，是哪里出了问题

**Comment by guolindev** [comment]
java.lang.NumberFormatException: Invalid int: "1.0"
问题很明显，litepal.xml里面version只能用整数，没有1.0这种用法。
