### ISSUE TITLE
关于saveOrUpdateAsync()用法

### ISSUE THREAD

**Issue by shuimuqinghua** [LitePalFramework/LitePal#204]
郭神，遇到个问题。我想用saveOrUpdateAsync()方法来处理数据，写法：areaModel.saveOrUpdateAsync("suoXie=? and areaName=? and code=? and quanPin=? and areaId=?", areaModel.getSuoXie(), areaModel.getAreaName(), areaModel.getCode(), areaModel.getQuanPin(), areaModel.getAreaId())
那么问题来了，我debug发现，进入不了onFinish()方法，数据也确实没有存入数据库中！
麻烦郭神看到了给点指示，谢谢！

**Comment by guolindev** [comment]
你后面要接一个listen()方法的，要不然不会执行的

**Comment by shuimuqinghua** [comment]
郭神，使用saveOrUpdateAsync还是有问题。
`java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
                                                                    at java.lang.Thread.nativeCreate(Native Method)
                                                                    at java.lang.Thread.start(Thread.java:1063)
                                                                    at org.litepal.crud.async.AsyncExecutor.execute(AsyncExecutor.java:45)
                                                                    at org.litepal.crud.async.SaveExecutor.listen(SaveExecutor.java:37)
                                                                    at com.udd.travel.UDDApplication$2.onResponse(UDDApplication.java:233)
                                                                    at com.udd.travel.UDDApplication$2.onResponse(UDDApplication.java:188)
                                                                    at com.zhy.http.okhttp.OkHttpUtils$3.run(OkHttpUtils.java:186)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)`

我写的代码如下：
`for (int i = 0; i < response.data.size(); i++) {
        
for (int j = 0; j < response.data.get(i).value.size(); j++) {
                                        final AreaModel areaModel = new AreaModel();
                                        areaModel.setType(1);
                                        areaModel.setAreaId(response.data.get(i).value.get(j).regionId);
                                        areaModel.setAreaName(response.data.get(i).value.get(j).regionName);
                                        areaModel.setAreaIndex(response.data.get(i).title);
                                        areaModel.saveOrUpdateAsync("areaId=?", areaModel.getAreaId())
                                                .listen(new SaveCallback() {
                                                    @Override
                                                    public void onFinish(boolean success) {
                                                        Logger.i("存储成功    ", areaModel.getAreaName());
                                                    }
                                                });
                                    }
  }`

但我不用这个方法，分别使用updateAsync跟saveAsync处理就没问题。

**Comment by guolindev** [comment]
竟然是OOM了，saveOrUpdateAsync这个方法确实要更耗内存，我估计是因为数据量过大了，saveOrUpdateAsync比updateAsync和saveAsync内存要耗得多得多，建议你数据量比较大的话还是别用这个方法，或者考虑将数据分段来执行。关于OOM的问题你可以参考下这条 https://github.com/LitePalFramework/LitePal/issues/138
