### ISSUE TITLE
org.litepal.exceptions.DatabaseGenerateException: can not find a class named org.litepal.model.Table_Schema

### ISSUE THREAD

**Issue by LinChSh** [LitePalFramework/LitePal#232]
06-24 15:41:52.933 E/AndroidRuntime( 7891): org.litepal.exceptions.DatabaseGenerateException: can not find a class named org.litepal.model.Table_Schema
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at org.litepal.b.aO(LitePalBase.java:196)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at org.litepal.b.aM(LitePalBase.java:123)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at org.litepal.d.f.hU(Generator.java:74)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at org.litepal.d.d.a(Creator.java:48)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at org.litepal.d.f.d(Generator.java:171)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at org.litepal.d.f.d(Generator.java:209)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at org.litepal.d.g.onCreate(LitePalOpenHelper.java:83)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at org.litepal.d.c.getWritableDatabase(Connector.java:58)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at org.litepal.d.c.getDatabase(Connector.java:81)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at com.android.bbklog.a.b.<init>(UploadDataBase.java:15)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at com.android.bbklog.b.a.cb(FeedBack.java:49)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at com.android.bbklog.dh.handleMessage(UploadService.java:776)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at android.os.Handler.dispatchMessage(Handler.java:102)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at android.os.Looper.loop(Looper.java:154)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at android.app.ActivityThread.main(ActivityThread.java:6235)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at java.lang.reflect.Method.invoke(Native Method)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)
06-24 15:41:52.933 E/AndroidRuntime( 7891):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)

**Comment by LinChSh** [comment]
调试了下 确实是混淆导致
proguard.flags里加入
-libraryjars libs/litepal-1.5.1.jar
-dontwarn org.litepal.**
-keep class org.litepal.** {*; }
就没这个问题了

感谢
