### ISSUE TITLE
概率性出现表不存在的bug

### ISSUE THREAD

**Issue by QuDump** [LitePalFramework/LitePal#258]
Caused by: android.database.sqlite.SQLiteException: no such table: trainstationcity (Sqlite code 1): , while compiling: SELECT * FROM trainstationcity WHERE cname like '%海口%', (OS error - 2:No such file or directory)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:897)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:508)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)

**Comment by guolindev** [comment]
你可以到数据库中看一下表存不存在，表不存在应该就是不存在，不会有什么概率的问题。 一般出现这种表不存在的情况，先检查一下你对应的实体类有没有，再检查这个实体类有没有配置到litepal.xml的映射列表当中。如果都配置正确的话通常还有一种情况，就是你的这个实体类是新增的，但是忘记把litepal.xml中的version加1了，因为litepal是不会实时检查你的实体类有没有发生变化的，只有你把version加1了之后，litepal才会去同步你的实体类和数据库表之间的映射。

**Comment by Beyond-Chao** [comment]
@guolindev 你好 我用的最新版本的 Litepal 也是报错。

    org.litepal.exceptions.LitePalSupportException: no such table: province (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM province ORDER BY id

按照你上面的操作都试了，还是不行，在安卓模拟器上试的。

**Comment by sunnnydaydev** [comment]
新增实体 版本+1 解决啦！ 多谢。
