### ISSUE TITLE
华为手机概率性出现，出现次数频繁，找不到原因，主要集中在6.0 7.0 系统

### ISSUE THREAD

**Issue by tianchong89** [LitePalFramework/LitePal#267]
org.litepal.exceptions.DataSupportException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at org.litepal.crud.DataHandler.query(DataHandler.java:151)
	at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
	at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:232)
	at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:194)

**Comment by guolindev** [comment]
这里有个帖子和你的问题应该是一样的
https://stackoverflow.com/questions/21432556/android-java-lang-illegalstateexception-couldnt-read-row-0-col-0-from-cursorw
问题是你一次性读取的数据过多了，CursorWindow中存储的数据是有限的。多利用条件查询语句来控制你一次性查询的数量，适当情况下使用分页，这样可以避免出现这种错误。

**Comment by tianchong89** [comment]
java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:507)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
	at org.litepal.crud.DataHandler.query(DataHandler.java:138)
	at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
	at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:232)
	at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:194)
	at net.strongsoft.waterstandardization.dailypatrol.projectcell.b.a(ProjectCellModel.java:135)

**Comment by tianchong89** [comment]
数据过长是不是也会引起这个情况
