### ISSUE TITLE
线程死锁问题

### ISSUE THREAD

**Issue by UFreedom** [LitePalFramework/LitePal#280]
```java
- waiting to lock <0x00da5fed> (a java.lang.Class<org.litepal.crud.DataSupport>) held by thread 87
  at java.lang.Class.forName(Class.java:324)
  at java.lang.Class.forName(Class.java:285)
  at org.litepal.LitePalBase.getSupportedFields(SourceFile:194)
  at org.litepal.LitePalBase.getTableModel(SourceFile:123)
  at org.litepal.tablemanager.Generator.getAllTableModels(SourceFile:74)
  at org.litepal.tablemanager.Creator.createOrUpgradeTable(SourceFile:48)
  at org.litepal.tablemanager.Generator.create(SourceFile:171)
  at org.litepal.tablemanager.Generator.create(SourceFile:209)
  at org.litepal.tablemanager.LitePalOpenHelper.onCreate(SourceFile:83)
  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
  - locked <0x04833e22> (a org.litepal.tablemanager.LitePalOpenHelper)
  at org.litepal.tablemanager.Connector.getWritableDatabase(SourceFile:64)
  - locked <0x091c00b3> (a java.lang.Class<org.litepal.tablemanager.Connector>)
  at org.litepal.tablemanager.Connector.getDatabase(SourceFile:87)
  at org.litepal.crud.ClusterQuery.find(SourceFile:222)
  - locked <0x06950670> (a org.litepal.crud.ClusterQuery)
  at org.litepal.crud.ClusterQuery.findLast(SourceFile:396)
```
```java 
at org.litepal.tablemanager.Connector.getWritableDatabase(SourceFile:63)
  - waiting to lock <0x091c00b3> (a java.lang.Class<org.litepal.tablemanager.Connector>) held by thread 1
  at org.litepal.tablemanager.Connector.getDatabase(SourceFile:87)
  at org.litepal.crud.DataSupport.deleteAll(SourceFile:1185)
  - locked <0x00da5fed> (a java.lang.Class<org.litepal.crud.DataSupport>)

```

业务场景：

- 子线程使用 DataSupport.deleteAll(A) 先删除 A ，然后使用 DataSupport.saveAll(A); 保存 A Model
- 主线程使用 DataSupport.where().findLast(B,true); 拉去 B Model

**Comment by Dkaishu** [comment]
你可以看看这个 https://github.com/LitePalFramework/LitePal/issues/115 @UFreedom
