### ISSUE TITLE
 Cursor window allocation of 2048 kb failed.

### ISSUE THREAD

**Issue by UFreedom** [LitePalFramework/LitePal#283]
```java

Fatal Exception: org.litepal.exceptions.DataSupportException: Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)
       at org.litepal.crud.DataHandler.query(SourceFile:153)
       at org.litepal.crud.QueryHandler.onFind(SourceFile:159)
       at org.litepal.crud.ClusterQuery.find(SourceFile:232)
       at org.litepal.crud.ClusterQuery$1.run(SourceFile:250)
       at java.lang.Thread.run(Thread.java:841)
Caused by org.litepal.exceptions.DataSupportException: Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)
       at org.litepal.crud.DataHandler.setAssociatedModel(SourceFile:1338)
       at org.litepal.crud.DataHandler.query(SourceFile:144)
       at org.litepal.crud.QueryHandler.onFind(SourceFile:159)
       at org.litepal.crud.ClusterQuery.find(SourceFile:232)
       at org.litepal.crud.ClusterQuery$1.run(SourceFile:250)
       at java.lang.Thread.run(Thread.java:841)
Caused by android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)
       at android.database.CursorWindow.(CursorWindow.java)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
       at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
       at org.litepal.crud.DataHandler.setAssociatedModel(SourceFile:1308)
       at org.litepal.crud.DataHandler.query(SourceFile:144)
       at org.litepal.crud.QueryHandler.onFind(SourceFile:159)
       at org.litepal.crud.ClusterQuery.find(SourceFile:232)
       at org.litepal.crud.ClusterQuery$1.run(SourceFile:250)
       at java.lang.Thread.run(Thread.java:841)


```

**Comment by guolindev** [comment]
应该是重复问题，参考下这里 https://github.com/LitePalFramework/LitePal/issues/249
