### ISSUE TITLE
查询数据崩溃的问题

### ISSUE THREAD

**Issue by guiying712** [LitePalFramework/LitePal#296]
10-08 11:36:59.676 11386-11386/com.hik.isms.dolphin E/AndroidRuntime:     at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                          at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                          at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                          at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                          at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                          at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                          at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                          at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                          at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                          at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                          at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                          at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                          at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                          at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                          at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                          at org.litepal.crud.DataHandler.query(DataHandler.java:138)
                                                                          at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:59)
                                                                          at org.litepal.crud.DataSupport.find(DataSupport.java:769)
                                                                          at org.litepal.crud.DataSupport.find(DataSupport.java:736)
                                                                          at hik.business.isms.video.data.RemoteVideoDataResource.getCollectResources(RemoteVideoDataResource.java:626)
                                                                          at hik.business.isms.video.resource.VideoResourcePresenter.getCollectResources(VideoResourcePresenter.java:55)
                                                                          at hik.business.isms.video.resource.VideoResourcePresenter.start(VideoResourcePresenter.java:28)
                                                                          at hik.business.isms.video.resource.VideoResourceActivity.onResume(VideoResourceActivity.java:36)
                                                                          at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
                                                                          at android.app.Activity.performResume(Activity.java:6849)
                                                                          at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3427)
                                                                          at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3490)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2755)
                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java)
10-08 11:36:59.676 11386-11386/com.hik.isms.dolphin E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1498)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:160)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6200)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
10-08 11:37:01.340 11386-11397/com.hik.isms.dolphin W/art: Suspending all threads took: 16.920ms
10-08 11:37:01.376 11386-11386/com.hik.isms.dolphin E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 24661732)
10-08 11:37:01.383 11386-11386/com.hik.isms.dolphin E/MQSEventManagerDelegate: reportJEEvent error happened:android.os.TransactionTooLargeException: data parcel size 24661732 bytes

保存和删除都没有问题，只要一查询就会发生崩溃。

**Comment by guolindev** [comment]
从日志上看，是发生StackOverflow了，这种情况我还是第一次见，可能是你的实体类定义的比较特殊。
能把你的实体类的完整代码贴出来一下吗？我得看看你的代码才能分析。

**Comment by guiying712** [comment]
public class LocalResource extends DataSupport　{

    private String indexCode;

    private String mName;

    private int mOrder;

    private String mParentIndexCode;

    private String mType;

    /*用户名*/
    private String userName = HiCoreServerClient.getInstance().getAccountInfo().getAccountName();

**Comment by laoshuzaiwojia** [comment]
怎么解决

**Comment by guiying712** [comment]
我也不知道怎么解决，用了最新版本就好了。

**Comment by guolindev** [comment]
此bug已在1.6.1版本中修复。
