### ISSUE TITLE
near "null": syntax error (code 1): , while compiling: INSERT INTO feed(null) VALUES (NULL)

### ISSUE THREAD

**Issue by drakeet** [LitePalFramework/LitePal#3]
I have a code: 
```java
for (Feed feed : feeds) {
    feed.save();
}
```
throws an android.database.sqlite.SQLiteException: 
```log
10-10 07:13:17.105    1468-1498/me.drakeet.***** E/SQLiteLog﹕ (1) near "null": syntax error
10-10 07:13:17.105    1468-1498/me.drakeet.***** E/SQLiteDatabase﹕ Error inserting
    android.database.sqlite.SQLiteException: near "null": syntax error (code 1): , while compiling: INSERT INTO feed(null) VALUES (NULL)
            at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
            at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
            at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
            at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
            at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
            at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1467)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
            at org.litepal.crud.SaveHandler.saving(SaveHandler.java:190)
            at org.litepal.crud.SaveHandler.doSaveAction(SaveHandler.java:151)
            at org.litepal.crud.SaveHandler.onSave(SaveHandler.java:79)
            at org.litepal.crud.DataSupport.saveThrows(DataSupport.java:1057)
            at org.litepal.crud.DataSupport.save(DataSupport.java:1020)
            at me.drakeet.*****.ui.fragment.MainFragment$2$1.doInBackground(MainFragment.java:193)
```
Does it belong to the library bug?  
Thanks!

**Comment by Goyohol** [comment]
同样的问题，哎~
