### ISSUE TITLE
Exception org.litepal.exceptions.DataSupportException: disk I/O error

### ISSUE THREAD

**Issue by nujnay** [LitePalFramework/LitePal#312]
出现先了这个问题 不知道怎么解决 在firebase上报错非常多

**Comment by guolindev** [comment]
只凭这段不是很好判断，还有更多日志信息吗？

**Comment by csbz17027** [comment]
E/SQLiteLog: (1802) os_unix.c:32285: (2) stat(/data/user/0/com.doujiaokeji.mengniu/databases/doujiaokeji_mengniu.db) - 
E/SQLiteLog: (1802) statement aborts at 36: [SELECT * FROM user ORDER BY id desc LIMIT 1] disk I/O error
E/SQLiteQuery: exception: disk I/O error (code 1802); query: SELECT * FROM user ORDER BY id desc LIMIT 1
E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.doujiaokeji.mengniu, PID: 25775
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.doujiaokeji.mengniu/com.doujiaokeji.mengniu.activities.MainActivity}: org.litepal.exceptions.DataSupportException: disk I/O error (code 1802)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2706)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:163)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6221)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
                                                    Caused by: org.litepal.exceptions.DataSupportException: disk I/O error (code 1802)
                                                       at org.litepal.crud.DataHandler.query(DataHandler.java:153)
                                                       at org.litepal.crud.QueryHandler.onFindLast(QueryHandler.java:97)
                                                       at org.litepal.crud.DataSupport.findLast(DataSupport.java:929)
                                                       at org.litepal.crud.DataSupport.findLast(DataSupport.java:900)
                                                       at com.doujiaokeji.sszq.common.SSZQBaseApplication.getUser(SSZQBaseApplication.java:139)
                                                       at com.doujiaokeji.mengniu.activities.MainActivity.initVariables(MainActivity.java:59)
                                                       at com.doujiaokeji.sszq.common.activities.SSZQBaseActivity.onCreate(SSZQBaseActivity.java:59)
                                                       at android.app.Activity.performCreate(Activity.java:6864)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                       at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:163) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6221) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by guolindev** [comment]
很抱歉，这个问题看上去更像是和具体手机设备的硬件有关，而不是LitePal封装的问题。如果是手机设备硬件方面的问题话，使用SQLiteDatabase原生的查询应该也一样会出错。

由于问题过去太久，我就先把问题关闭了，假如还有人关注这个问题的话，请再重新打开。
