### ISSUE TITLE
Cursor window allocation of 2048 kb failed

### ISSUE THREAD

**Issue by animus198656** [LitePalFramework/LitePal#317]
看到之前有人提问了同样的问题，但没得到解答，我这也出现了。

出错代码片段：

            SwitchDBUtil.switchDefaultDB();
            if (DataSupport.isExist(DBBookEntry.class, "bookid = ?", book.getBookid())) {
                SwitchDBUtil.switchEngineDB(this);
                if (DataSupport.isExist(EngineEBookEntry.class, "bookid = ?", book.getBookid())) {
                     .........
                }
           }

代码描述：业务需要创建了两个数据库，在做数据库切换后进行isExist()查询的时候出错，由于是友盟统计出来的错误，不清楚是第一次isExist()是出错还是第二次isExist() .这段代码是在Activity退出时调用的。

错误是偶发的，友盟统计结果显示出错率很高，但是我复现不出来。

异常信息：
org.litepal.exceptions.DataSupportException: Cursor window allocation of 2048 kb failed. 
	at org.litepal.crud.DataHandler.mathQuery(DataHandler.java)
	at org.litepal.crud.QueryHandler.onCount(QueryHandler.java)
	at org.litepal.crud.ClusterQuery.count(ClusterQuery.java)
	at org.litepal.crud.ClusterQuery.count(ClusterQuery.java)
	at org.litepal.crud.DataSupport.isExist(DataSupport.java)
	at com.search360.book.Reader360Activity.onBackGround(Reader360Activity.java)
	at org.cocos2dx.lib.Cocos2dxRenderer.nativeOnPause(Cocos2dxRenderer.java)
	at org.cocos2dx.lib.Cocos2dxRenderer.handleOnPause(Cocos2dxRenderer.java)
	at org.cocos2dx.lib.Cocos2dxGLSurfaceView$4.run(Cocos2dxGLSurfaceView.java)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1509)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)
Caused by: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
	at android.database.CursorWindow.<init>(CursorWindow.java:108)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:225)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:149)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:143)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
	... 11 more
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
	at android.database.CursorWindow.<init>(CursorWindow.java:108)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:225)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:149)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:143)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
	at org.litepal.crud.DataHandler.mathQuery(DataHandler.java)
	at org.litepal.crud.QueryHandler.onCount(QueryHandler.java)
	at org.litepal.crud.ClusterQuery.count(ClusterQuery.java)
	at org.litepal.crud.ClusterQuery.count(ClusterQuery.java)
	at org.litepal.crud.DataSupport.isExist(DataSupport.java)
	at com.search360.book.Reader360Activity.onBackGround(Reader360Activity.java)
	at org.cocos2dx.lib.Cocos2dxRenderer.nativeOnPause(Cocos2dxRenderer.java)
	at org.cocos2dx.lib.Cocos2dxRenderer.handleOnPause(Cocos2dxRenderer.java)
	at org.cocos2dx.lib.Cocos2dxGLSurfaceView$4.run(Cocos2dxGLSurfaceView.java)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1509)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

**Comment by flyingegret** [comment]
I met this problem again,but haven't found useful solution!

**Comment by wilson123** [comment]
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
	at android.database.CursorWindow.<init>(CursorWindow.java:108)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:140)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:134)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:264)
	at org.litepal.crud.DataHandler.query(DataHandler.java:134)
	at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
	at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:232)
	at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:194)
	at org.litepal.crud.DataSupport.saveOrUpdate(DataSupport.java:1934)
	at org.litepal.crud.DataSupport$20.run(DataSupport.java:1977)
	at java.lang.Thread.run(Thread.java:760)

我这也出现这样的问题

**Comment by af8600** [comment]
我增经有出现过这个问题，后来是因为其它地方产生的内存泄漏引起的，内存泄漏解决后，这个问题再没有出现。

**Comment by guolindev** [comment]
重复问题，见这里 https://github.com/LitePalFramework/LitePal/issues/576
