### ISSUE TITLE
libcore.reflect.GenericArrayTypeImpl cannot be cast to java.lang.Class

### ISSUE THREAD

**Issue by qzyse2017** [LitePalFramework/LitePal#331]
Process: com.example.weeat, PID: 6801
                                                                     java.lang.ClassCastException: libcore.reflect.GenericArrayTypeImpl cannot be cast to java.lang.Class
                                                                         at org.litepal.LitePalBase.getGenericTypeClass(LitePalBase.java:316)
                                                                         at org.litepal.LitePalBase.getGenericTypeName(LitePalBase.java:672)
                                                                         at org.litepal.LitePalBase.manyToAnyConditions(LitePalBase.java:567)
                                                                         at org.litepal.LitePalBase.analyzeClassFields(LitePalBase.java:390)
                                                                         at org.litepal.LitePalBase.getAssociations(LitePalBase.java:149)
                                                                         at org.litepal.tablemanager.Generator.getAllAssociations(Generator.java:88)
                                                                         at org.litepal.tablemanager.AssociationCreator.addOrUpdateAssociation(AssociationCreator.java:60)
                                                                         at org.litepal.tablemanager.Generator.addAssociation(Generator.java:132)
                                                                         at org.litepal.tablemanager.Generator.create(Generator.java:210)
                                                                         at org.litepal.tablemanager.LitePalOpenHelper.onCreate(LitePalOpenHelper.java:83)
                                                                         at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
                                                                         at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                         at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:64)
                                                                         at org.litepal.tablemanager.Connector.getDatabase(Connector.java:87)
                                                                         at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:222)
                                                                         at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:194)
                                                                         at com.example.weeat.datalink.UserState.Login(UserState.java:21)
                                                                         at com.example.weeat.userInterface.LoginActivity$3.onClick(LoginActivity.java:64)
怀疑是我的类设置有问题，但是实在分不清哪里有问题，想请教下您
public class User extends DataSupport
{
    @Column(unique = true)
    private String UserName;

    private byte[] UserAvatar;
    private String PasswordMd5;
    private Date RegisterTime;
    private ArrayList<Topic> OwnedTopic = new ArrayList<>();
    private Character Sex;
    private String Region;
    private boolean AvailFlag;
    private ArrayList<User> Friends = new ArrayList<>();
    private ArrayList<User> requestFriends = new ArrayList<>();
    private ArrayList<User> BlockedUsers = new ArrayList<>();
    private ArrayList<Message> MessageBox = new ArrayList<>();
...
}

**Comment by qzyse2017** [comment]
上面应该是在第一次查询操作的时候发生的

**Comment by R-Junko** [comment]
我也是这个问题
