### ISSUE TITLE
报 java.lang.NoClassDefFoundError: org.litepal.parser.LitePalAttr

### ISSUE THREAD

**Issue by 852172891** [LitePalFramework/LitePal#335]
问题描述： 在平版（Spreadturm T101）上使用 报 java.lang.NoClassDefFoundError: org.litepal.parser.LitePalAttr，在手机上就没问题，另外 另一个程序也使用了litepal 装在平板上是正常的
                                                                               at org.litepal.tablemanager.Connector.buildConnection(Connector.java:104)
                                                                               at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:63)
                                                                               at org.litepal.tablemanager.Connector.getDatabase(Connector.java:87)
                                                                               at org.litepal.crud.DataSupport.saveThrows(DataSupport.java:1872)
                                                                               at org.litepal.crud.DataSupport.save(DataSupport.java:1812)

**Comment by dom4j1** [comment]
请问这个问题 您是怎么解决的

**Comment by changfeng1050** [comment]
请问这个问题 您是怎么解决的，我发现在Android 4.2.2和Android4.4.4上都会出现这个问题，在Android5.1上不会出现
