### ISSUE TITLE
递归类创建数据库报错

### ISSUE THREAD

**Issue by StormKid** [LitePalFramework/LitePal#336]
**递归类代码如下：**
```
public class ClassifyData extends DataSupport implements Serializable{

    @Column(unique = true)
    private String classifyId;
    private String name;
    private List<ClassifyData>  children;

    public String getId() {
        return classifyId;
    }

    public void setId(String classifyId) {
        this.classifyId = classifyId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<ClassifyData> getChildren() {
        return children;
    }

    public void setChildren(List<ClassifyData> children) {
        this.children = children;
    }
```

**报错的log：**
```
 FATAL EXCEPTION: main
Process: com.xxx.xxxx:channel, PID: 6224
java.lang.RuntimeException: Unable to create application com.xxx.xxxx.MyApplication: org.litepal.exceptions.DatabaseGenerateException: An exception that indicates there was an error with SQL parsing or execution. create table classifydata_classifydata (classifydata_id integer, classifydata_id integer)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
at android.app.ActivityThread.-wrap2(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: org.litepal.exceptions.DatabaseGenerateException: An exception that indicates there was an error with SQL parsing or execution. create table classifydata_classifydata (classifydata_id integer, classifydata_id integer)
at org.litepal.tablemanager.Generator.execute(Generator.java:117)
at org.litepal.tablemanager.AssociationCreator.createIntermediateTable(AssociationCreator.java:336)
at org.litepal.tablemanager.AssociationCreator.addAssociations(AssociationCreator.java:290)
at org.litepal.tablemanager.AssociationCreator.addOrUpdateAssociation(AssociationCreator.java:60)
at org.litepal.tablemanager.Generator.addAssociation(Generator.java:132)
at org.litepal.tablemanager.Generator.create(Generator.java:210)
at org.litepal.tablemanager.LitePalOpenHelper.onCreate(LitePalOpenHelper.java:83)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:64)
at org.litepal.tablemanager.Connector.getDatabase(Connector.java:87)
at com.xxx.xxxx.MyApplication.onCreate(MyApplication.kt:13)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
at android.app.ActivityThread.-wrap2(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6119) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by DQ2020** [comment]
我也出现了这个问题 如何解决？

**Comment by DQ2020** [comment]
我也出现了这个问题 如何解决？

**Comment by DQ2020** [comment]
我也出现了这个问题 如何解决？

**Comment by StormKid** [comment]
@DQ2020 没有解决，我现在没在搞数据库这块，推荐还是使用GreenDao吧，kotlin推荐用kotlin自带的sqlite库，写法很简单。

**Comment by canglen** [comment]
同遇到这个问题，等待郭神解决。

**Comment by canglen** [comment]
1.5.1没有这个问题。1.6.1出现了这个问题。
导出1.5.1版本的数据库查看发现是没有把递归关联自己的这个情况写入外键的。
1.6.1可能在这一块进行了修改，单是没有考虑外键id的问题。所以出现了这个情况。
遇到了这个问题，所以分析下。希望可以给郭神提供到一点帮助。

**Comment by guolindev** [comment]
此问题已在LitePal 2.0.0版本中修复。

**Comment by StormKid** [comment]
@guolindev 开始使用2.0.0
