### ISSUE TITLE
查询数据导致应用崩溃问题

### ISSUE THREAD

**Issue by Orankarl** [LitePalFramework/LitePal#341]
本来运行正常，刚刚改动一些无关地方后测试发现每次查询都会导致崩溃。
`12-30 21:48:13.256 11149-11149/com.example.orankarl.ddls E/AndroidRuntime:     at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)
                                                                               at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:633)
                                                                               at org.litepal.crud.DataHandler.getInitParamValue(DataHandler.java:946)
                                                                               at org.litepal.crud.DataHandler.getConstructorParams(DataHandler.java:691)`
litepal版本为1.6.1。
向数据库添加数据和聚合函数调用都没有问题。

**Comment by Orankarl** [comment]
又测试了几次，发现只有其中一个实体类对应Table中有数据时，查询该Table会导致崩溃，其他实体类无影响。该实体类代码如下：

`public class Deadline extends DataSupport {

    private long id;
    private long calendarMillis;
    private String title;
    private String info;
    private String userName;

    public Deadline(long calendarMillis, String title, String info, String userName) {
        this.calendarMillis = calendarMillis;
        this.title = title;
        this.info = info;
        this.userName = userName;
    }

    public Deadline(Deadline deadline) {
        this.id = deadline.getId();
        this.calendarMillis = deadline.getCalendarMillis();
        this.title = deadline.getTitle();
        this.info = deadline.getInfo();
        this.userName = deadline.getUserName();
    }

    public Deadline(FinishedDeadline finishedDeadline) {
        this.id = finishedDeadline.getId();
        this.calendarMillis = finishedDeadline.getCalendarMillis();
        this.title = finishedDeadline.getTitle();
        this.info = finishedDeadline.getInfo();
        this.userName = finishedDeadline.getUserName();
    }

    public long getId() {
        return id;
    }

    public long getCalendarMillis() {
        return calendarMillis;
    }

    public void setCalendarMillis(long calendarMillis) {
        this.calendarMillis = calendarMillis;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
}`

**Comment by guolindev** [comment]
更新一下版本就可以了，和这个问题应该是一样的。
https://github.com/LitePalFramework/LitePal/issues/313
