### ISSUE TITLE
部分手机上空指针异常

### ISSUE THREAD

**Issue by na0015** [LitePalFramework/LitePal#349]
java.lang.NullPointerException 							
	at java.util.regex.Matcher.reset(Matcher.java:177) 							
	at java.util.regex.Matcher.<init>(Matcher.java:90) 							
	at java.util.regex.Pattern.matcher(Pattern.java:297) 							
	at org.litepal.util.DBUtility.convertWhereClauseToColumnName(DBUtility.java:486) 							
	at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:156) 							
	at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:232) 							
	at org.litepal.crud.ClusterQuery.find(ClusterQuery.java:194) 							
	at com.hdtytech.ybss.dao.XzjdDao.getList(XzjdDao.java:27) 							
	at com.hdtytech.ybss.viewmodle.XzjdViewModle$1.run(XzjdViewModle.java:27)  							
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 							
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 							
	at java.lang.Thread.run(Thread.java:841)

**Comment by guolindev** [comment]
出现这个错误肯定是因为你在查询的表达式里面传入了null，比如说出现了DataSupport.where(null)这样的语句。部分手机上才出现，那就说明这个查询的条件你是动态传入的，受一些条件的影响比如说服务器返回的数据。所以你应该在外部加上条件的非空判断，因为给where()方法传个null是没有任何意义的。

当然为了防止以后有别人也遇到同样的问题，我在LitePal内部也加上了一个非空检查，会在下个版本发布的时候修复掉这个问题。暂时对于你来说，对条件判断一下非空状态就可以解决这个问题了。
