### ISSUE TITLE
list<String>

### ISSUE THREAD

**Issue by yuewe** [LitePalFramework/LitePal#361]
kotlin bean对象中有list<String>字段，DataSupport.findAll或DataSupport.deleteAll一直又问题，

**Comment by guolindev** [comment]
具体是有什么问题说一下，要不然我没办法定位。

**Comment by yuewe** [comment]
我是用kotlin写的，data类代码：
data class DevicesData(
        val createtime: String, //null
        val createuser: String, //null
        val equipname: String, //
        val equipno: String, //
        val groupId: String, //null
        val groupname: String, //null
        @SerializedName("id")
        val deviceId: String, //24
        val linkage: String, //null
        val runStatus: String, //null
        val status: String, //1
        //@Column(nullable = true)
        **var threshold: List<String>,**
        val updatetime: String, //null
        val updateuser: String, //null
        val userId: String, //null
        val username: String, //null
        val vestingGroup: String, //null
        val vestingGroupName: String //null
) : DataSupport()
@guolindev

**Comment by yuewe** [comment]
就是save的时候有问题。

**Comment by yuewe** [comment]
报错代码：
 Caused by: org.litepal.exceptions.DataSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
                      at org.litepal.crud.DataHandler.query(DataHandler.java:153)
                      at org.litepal.crud.QueryHandler.onFindAll(QueryHandler.java:123)
                      at org.litepal.crud.DataSupport.findAll(DataSupport.java:1028)
                      at org.litepal.crud.DataSupport.findAll(DataSupport.java:994)
                      at com.yuewe.cleanmvp.presentation.presenter.impl.GetDevicePresenter.handleLoginResponse(GetDevicePresenter.kt:48)
                      at com.yuewe.cleanmvp.presentation.presenter.impl.GetDevicePresenter$GetDeviceObserver.onNext(GetDevicePresenter.kt:107)
                      at com.yuewe.cleanmvp.presentation.presenter.impl.GetDevicePresenter$GetDeviceObserver.onNext(GetDevicePresenter.kt:99)
                      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
                      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                      at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                      at android.os.Handler.handleCallback(Handler.java:751) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:159) 
                      at android.app.ActivityThread.main(ActivityThread.java:6355) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883) 
                   Caused by: org.litepal.exceptions.DataSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
                      at org.litepal.crud.DataHandler.createInstanceFromClass(DataHandler.java:635)
                      at org.litepal.crud.DataHandler.query(DataHandler.java:138)
                      at org.litepal.crud.QueryHandler.onFindAll(QueryHandler.java:123) 
                      at org.litepal.crud.DataSupport.findAll(DataSupport.java:1028) 
                      at org.litepal.crud.DataSupport.findAll(DataSupport.java:994) 
                      at com.yuewe.cleanmvp.presentation.presenter.impl.GetDevicePresenter.handleLoginResponse(GetDevicePresenter.kt:48) 
                      at com.yuewe.cleanmvp.presentation.presenter.impl.GetDevicePresenter$GetDeviceObserver.onNext(GetDevicePresenter.kt:107) 
                      at com.yuewe.cleanmvp.presentation.presenter.impl.GetDevicePresenter$GetDeviceObserver.onNext(GetDevicePresenter.kt:99) 
                      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200) 
                      at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252) 
                      at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109) 
                      at android.os.Handler.handleCallback(Handler.java:751) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:159) 
                      at android.app.ActivityThread.main(ActivityThread.java:6355) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by yuewe** [comment]
只要我把数据类中的var threshold: List去掉，然后重新建表，重新加数据就没问题，查询和删除就没问题。

**Comment by guolindev** [comment]
你这个List没指定泛型啊，你加上泛型再试一下呢
