### ISSUE TITLE
DataSupportException,求大神帮忙

### ISSUE THREAD

**Issue by kotlindev** [LitePalFramework/LitePal#377]
我把ClassInfo对象保存到另一个对象中，我要把它保存到SQLite中，获取ClassInfo对象之后，调用save方法：
```
ClassInfo classInfo = respOfGetClassInfo.getClassInfo();
 Log.i(TAG, "班级信息：名" + classInfo.getClassName() + ",描述" + classInfo.getClassDes());
 classInfo.save();
```
但是调用save方法后报错，请大神帮忙
```
--------- beginning of crash
04-20 07:21:35.453 3205-3205/xyz.wkmf.wkmf E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xyz.wkmf.wkmf, PID: 3205
    org.litepal.exceptions.DataSupportException: can not find a class named 英语1班
        at org.litepal.crud.DataSupport.saveThrows(DataSupport.java:1880)
        at xyz.wkmf.wkmf.pager.imple.HomePager.saveData(HomePager.java:78)
        at xyz.wkmf.wkmf.pager.imple.HomePager.access$200(HomePager.java:39)
        at xyz.wkmf.wkmf.pager.imple.HomePager$1.handleMessage(HomePager.java:63)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: org.litepal.exceptions.DatabaseGenerateException: can not find a class named 英语1班
        at org.litepal.LitePalBase.getSupportedFields(LitePalBase.java:196)
        at org.litepal.crud.SaveHandler.onSave(SaveHandler.java:87)
        at org.litepal.crud.DataSupport.saveThrows(DataSupport.java:1876)
        at xyz.wkmf.wkmf.pager.imple.HomePager.saveData(HomePager.java:78) 
        at xyz.wkmf.wkmf.pager.imple.HomePager.access$200(HomePager.java:39) 
        at xyz.wkmf.wkmf.pager.imple.HomePager$1.handleMessage(HomePager.java:63) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
       
    --------- beginning of system
```

对应的DataSupport派生类如下

```
public class ClassInfo extends DataSupport{
    private int classId;//班级id
    private String className;//班级名
    private String classDes;//班级描述
    private String invite_code;//邀请码
    private String teacherName;//教师名
    private String teacherGender;//教师性别

    public int getClassId() {
        return classId;
    }

    public void setClassId(int classId) {
        this.classId = classId;
    }

    @Override
    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public String getClassDes() {
        return classDes;
    }

    public void setClassDes(String classDes) {
        this.classDes = classDes;
    }

    public String getInvite_code() {
        return invite_code;
    }

    public void setInvite_code(String invite_code) {
        this.invite_code = invite_code;
    }

    public String getTeacherName() {
        return teacherName;
    }

    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    public String getTeacherGender() {
        return teacherGender;
    }

    public void setTeacherGender(String teacherGender) {
        this.teacherGender = teacherGender;
    }
}
```

**Comment by kotlinup** [comment]
问题已经解决了，所有数据库字段改成小写就可以
```
public class ClassInfo extends DataSupport{
    private String class_id;//班级id
    private String class_name;//班级名称
    private String des;//班级描述
    private String invite_code;//班级邀请码
    private String teacher_name;//教师姓名
    private String teacher_gender;//教师性别

    public String getClass_id() {
        return class_id;
    }

    public void setClass_id(String class_id) {
        this.class_id = class_id;
    }

    public String getClass_name() {
        return class_name;
    }

    public void setClass_name(String class_name) {
        this.class_name = class_name;
    }

    public String getDes() {
        return des;
    }

    public void setDes(String des) {
        this.des = des;
    }

    public String getInvite_code() {
        return invite_code;
    }

    public void setInvite_code(String invite_code) {
        this.invite_code = invite_code;
    }

    public String getTeacher_name() {
        return teacher_name;
    }

    public void setTeacher_name(String teacher_name) {
        this.teacher_name = teacher_name;
    }

    public String getTeacher_gender() {
        return teacher_gender;
    }

    public void setTeacher_gender(String teacher_gender) {
        this.teacher_gender = teacher_gender;
    }
}
```

调用处：
```
ClassInfo classInfo = respOfGetClassInfo.getClassInfo();
        boolean save = classInfo.save();
        Log.i(TAG,"班级信息保存结果："+save);
```

**Comment by paihuai00** [comment]
也遇到了这个问题，其实是 "className"，这里出问题了。。。

**Comment by kotlinup** [comment]
我改一下数据库字段就好了，你可以尝试一下看有没有用，更改之后，删除APP，重新编译安装：

我原本的代码如下：
public class ClassInfo extends DataSupport{     private int classId;//班级id     private String className;//班级名     private String classDes;//班级描述     private String invite_code;//邀请码     private String teacherName;//教师名     private String teacherGender;//教师性别......}


更改后的代码如下，希望能帮到你：
public class ClassInfo extends DataSupport{     private int classId;//班级id     private String class_name;//班级名     private String class_des;//班级描述     private String invite_code;//邀请码     private String teacher_name;//教师名     private String teacher_gender;//教师性别......｝

**Comment by xiexin52k** [comment]
看到 "getClassName"上面的"@Override"注解没? 如果你重写了这个函数, 那么返回的类名就会有问题, 正确的应该是获取到com.xxx.xxx, 但是你重写了, 就会返回字段信息, 只要把这个getClassName改一下就行. 字段可以不用改.
