### ISSUE TITLE
InvalidAttributesException

### ISSUE THREAD

**Issue by hearsilent** [LitePalFramework/LitePal#381]
LitePal version 1.6.1

```
Caused by org.litepal.exceptions.InvalidAttributesException: dbname is empty or not defined in litepal.xml file, or your litepal.xml file is missing.
       at org.litepal.parser.LitePalAttr.checkSelfValid(LitePalAttr.java:197)
       at org.litepal.tablemanager.Connector.buildConnection(Connector.java:105)
       at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:63)
       at org.litepal.tablemanager.Connector.getDatabase(Connector.java:87)
       at org.litepal.crud.DataSupport.findAll(DataSupport.java:1027)
       at org.litepal.crud.DataSupport.findAll(DataSupport.java:994)
```

My litepal.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<litepal>

	<dbname value="BusData"/>

	<version value="9"/>

	<list>
		<mapping class="hearsilent.busplus.models.BusRouteModel"/>
		<mapping class="hearsilent.busplus.models.BusStopModel"/>
		<mapping class="hearsilent.busplus.models.BusCollectionModel"/>
		<mapping class="hearsilent.busplus.models.BusStopCollectionModel"/>
		<mapping class="hearsilent.busplus.models.BusStopWidgetModel"/>
		<mapping class="hearsilent.busplus.models.BikeCollectionModel"/>
		<mapping class="hearsilent.busplus.models.BikeNearbyWidgetModel"/>
		<mapping class="hearsilent.busplus.models.SuggestionModel"/>
		<mapping class="hearsilent.busplus.models.TerminiSuggestionModel"/>
		<mapping class="hearsilent.busplus.models.PredictionModel"/>
	</list>

</litepal>
```

**Comment by guolindev** [comment]
litepal.xml文件配置没什么问题，那应该就是文件位置的问题了。litepal.xml需要放到assets目录的下面。assets目录是java、res这些目录同级的。
