### ISSUE TITLE
AppCrash

### ISSUE THREAD

**Issue by ohappcrash** [LitePalFramework/LitePal#385]
Cursor window allocation of 2048 kb failed. 

org.litepal.exceptions.DataSupportException:Cursor window allocation of 2048 kb failed.
--
2 org.litepal.crud.DataHandler.query(DataHandler.java:151)
3 ......
4 Caused by:
5 android.database.CursorWindowAllocationException:Cursor window allocation of 2048 kb failed.
6 android.database.CursorWindow.<init>(CursorWindow.java:108)
7 android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
8 android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
9 android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
10 android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
11 android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
12 org.litepal.crud.DataHandler.query(DataHandler.java:132)
13 org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
14 org.litepal.crud.ClusterQuery.find(ClusterQuery.java:232)
15 org.litepal.crud.ClusterQuery.findFirst(ClusterQuery.java:312)
16 org.litepal.crud.ClusterQuery.findFirst(ClusterQuery.java:284)

**Comment by hezyuan** [comment]
出错堆栈

1	org.litepal.exceptions.DataSupportException:unable to open database file (code 2062)
2	#################################################################
3	Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
4	Caused By : Application has opened too many files. Maximum of available file descriptors in one process is 1024 in default.
5	(unable to open database file (code 2062))
6	#################################################################
7	org.litepal.crud.DataHandler.query(DataHandler.java:151)
8	......
9	Caused by:
10	android.database.sqlite.SQLiteCantOpenDatabaseException:unable to open database file (code 2062)
11	#################################################################
12	Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
13	Caused By : Application has opened too many files. Maximum of available file descriptors in one process is 1024 in default.
14	(unable to open database file (code 2062))
15	#################################################################
16	android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
17	android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1017)
18	android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
19	android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
20	android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:152)

**Comment by CoderDaMing** [comment]
> 4	Caused By : Application has opened too many files. Maximum of available file descriptors in one process is

我也遇到了相同的crash

**Comment by xiexin52k** [comment]
我也有这个Crash
```
android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:732)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1576)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1522)
	at org.litepal.crud.UpdateHandler.doUpdateAllAction(UpdateHandler.java:202)
	at org.litepal.crud.UpdateHandler.onUpdateAll(UpdateHandler.java:181)
	at org.litepal.Operator.updateAll(Operator.java:1546)
	at org.litepal.Operator.updateAll(Operator.java:1486)
	at org.litepal.LitePal.updateAll(LitePal.java:1070)
	at com.enable.serviceframework.compat.v3.transfer.core.ServiceDownloadManager.startAllDownload(ServiceDownloadManager.java:216)
	at com.enable.serviceframework.compat.v3.transfer.core.ServiceDownloadManager.handleMessage(ServiceDownloadManager.java:102)
	at com.enable.serviceframework.utils.remoteutils.server.RemoteServiceHelper.handleMessage(RemoteServiceHelper.java:82)
	at com.enable.serviceframework.utils.remoteutils.common.RemoteMessageManager.handleMessage(RemoteMessageManager.java:101)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by androidVHappy** [comment]
我也遇到过这个crash   怎么处理

**Comment by guolindev** [comment]
重复问题，见这里 https://github.com/LitePalFramework/LitePal/issues/576
