### ISSUE TITLE
 @Column(unique = true)后多次调用saveAll崩溃

### ISSUE THREAD

**Issue by 15260957387** [LitePalFramework/LitePal#398]
将某个字段设置为 @Column(unique = true)后多次调用LitePal.saveAll崩溃
org.litepal.exceptions.LitePalSupportException: Save current model failed.
	at org.litepal.LitePal.saveAll(LitePal.java:1622)
	at com.makeart2017.Fragment.IMFriendsFragment$4.success(IMFriendsFragment.java:352)
	at com.makeart2017.initmtop.MtopRequestFactory$1.handleMessage(MtopRequestFactory.java:77)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5571)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
Caused by: org.litepal.exceptions.LitePalSupportException: Save current model failed.
	at org.litepal.crud.SaveHandler.throwIfSaveFailed(SaveHandler.java:337)
	at org.litepal.crud.SaveHandler.afterSave(SaveHandler.java:221)
	at org.litepal.crud.SaveHandler.doSaveAction(SaveHandler.java:163)
	at org.litepal.crud.SaveHandler.onSaveAll(SaveHandler.java:125)
	at org.litepal.LitePal.saveAll(LitePal.java:1619)
	... 8 more

**Comment by 15260957387** [comment]
@Column(unique = true)
    private long friendId;
friendId是一样的，多次LitePal.saveAll()崩溃

**Comment by ShengjieGeng** [comment]
这个有什么疑问吗，既然是unique了，出现了同样的值肯定报错的。 #

**Comment by ihewro** [comment]
为啥 catch 不到这个异常LitePalSupportException 咧

**Comment by 15260957387** [comment]
知道了，谢谢

**Comment by yeshengwu** [comment]
那有uninqe的多次保存怎么做？ 先本地查找再更新？
