### ISSUE TITLE
LitePalSupportException: disk I/O error

### ISSUE THREAD

**Issue by xiexin52k** [LitePalFramework/LitePal#431]
```
09-07 15:13:45.988 25784-32258/com.enable.serviceframework E/SQLiteLog: (1802) os_unix.c:29136: (2) fstat(/storage/emulated/0/LearningShell/8JQ3T0000000000000904/.db/8JQ3T0000000000000904.db) - 
09-07 15:13:45.989 25784-32258/com.enable.serviceframework E/SQLiteLog: (1802) statement aborts at 21: [SELECT * FROM studentclassinfo ORDER BY id] disk I/O error
09-07 15:13:45.989 25784-32258/com.enable.serviceframework E/SQLiteQuery: exception: disk I/O error (code 1802); query: SELECT * FROM studentclassinfo ORDER BY id
09-07 15:13:46.002 25784-32258/com.enable.serviceframework E/AndroidRuntime: FATAL EXCEPTION: Thread-790
    Process: com.enable.serviceframework, PID: 25784
    org.litepal.exceptions.LitePalSupportException: disk I/O error (code 1802)
        at org.litepal.crud.DataHandler.query(DataHandler.java:154)
        at org.litepal.crud.QueryHandler.onFindAll(QueryHandler.java:123)
        at org.litepal.LitePal.findAll(LitePal.java:1114)
        at org.litepal.LitePal.findAll(LitePal.java:1079)
        at com.enable.serviceframework.response.ResponseStudentClass.handlerData(ResponseStudentClass.java:36)
        at com.enable.serviceframework.response.base.ResponseManger$ResponseThread.run(ResponseManger.java:214)
     Caused by: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1802)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:843)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
        at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
        at org.litepal.crud.DataHandler.query(DataHandler.java:135)
        at org.litepal.crud.QueryHandler.onFindAll(QueryHandler.java:123) 
        at org.litepal.LitePal.findAll(LitePal.java:1114) 
        at org.litepal.LitePal.findAll(LitePal.java:1079) 
        at com.enable.serviceframework.response.ResponseStudentClass.handlerData(ResponseStudentClass.java:36) 
        at com.enable.serviceframework.response.base.ResponseManger$ResponseThread.run(ResponseManger.java:214) 
```

报错代码是
```java
 List<StudentClassInfo> classInfoList = LitePal.findAll(StudentClassInfo.class);
```
有好几回了. 是忽然就报, 没有什么规律.

**Comment by guolindev** [comment]
这个问题基本都是死锁的原因导致的，我也没办法帮你定位锁的原因，因为看不到你的代码，我把网上几篇解决问题的链接发给你，看看有没有什么帮助吧。
https://blog.csdn.net/iamcxl369/article/details/72637429
https://stackoverflow.com/questions/21554277/android-sqlite-database-sqlitediskioexception-disk-i-o-error-code-1802
