### ISSUE TITLE
概率性出现Caused by: android.database.CursorWindowAllocationException: Cursor window allocation of 4096 kb failed. # Open Cursors=518 (# cursors opened by this proc=518)

### ISSUE THREAD

**Issue by wilson123** [LitePalFramework/LitePal#437]
Caused by: android.database.CursorWindowAllocationException: Cursor window allocation of 4096 kb failed. # Open Cursors=518 (# cursors opened by this proc=518)
	at android.database.CursorWindow.<init>(CursorWindow.java:108)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
	at org.litepal.crud.DataHandler.query(DataHandler.java:135)
	... 20 more

**Comment by guolindev** [comment]
见回复 https://github.com/LitePalFramework/LitePal/issues/576
