### ISSUE TITLE
是否可以不把错误日志吃掉

### ISSUE THREAD

**Issue by FJCDrome** [LitePalFramework/LitePal#474]
litepal很多地方都会catch异常,然后抛出一个自己的异常
使用过程中遇到过一些问题,经常在调试的时候发现看不到最原始的那个异常的日志.
例如:今天引了一个新的jar包,结果直接编译运行没问题,正式包就出问题了.竟然是提示litepal.xml格式有问题(为啥会这样还不知道)然后我检查了新的apk包中的litepal.xml和老的包里的一模一样,找问题就变得很麻烦了

并不是说litepal有什么bug,只是小小的建议下,即使想要catch异常然后抛出自己的异常,是否可以考虑下将原来的异常日志也打印一下,对于调试一些莫名其妙的问题或许会有帮助,谢谢

**Comment by FJCDrome** [comment]
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml: <?xml version="1.0" encoding="utf-8"?>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml: <litepal>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:     <dbname value="cashierDB" ></dbname>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:     
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:     <version value="87" ></version>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:     <list>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.Cashier"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.Customer"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.RetailItem"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.RetailOrder"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.RetailOrderItem"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.ScheduleTask"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.SystemSyncSetting"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.CashierAd"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.AssociateReport"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.ShopAssociate"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.CashierAdRecord"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.RechargeOrderRecord"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.CashierError"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.dispatch.DispatchOrderShortInfor"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.Category"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.TableDO"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:         <mapping class="com.wbm.lib_base_service.business.model.SalesmanDO"></mapping>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml:     </list>
2018-11-26 16:50:36.951 15142-15142/? E/litepal.xml: </litepal>
2018-11-26 16:50:37.016 15142-15142/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2018-11-26 16:50:37.017 15142-15142/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wbm.app.activity, PID: 15142
    java.lang.RuntimeException: Unable to create application com.wbm.app.application.MyApplication: org.litepal.exceptions.ParseConfigurationFileException: can not parse the litepal.xml, check if it's in correct format
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5424)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1547)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6137)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: org.litepal.exceptions.ParseConfigurationFileException: can not parse the litepal.xml, check if it's in correct format
        at org.litepal.parser.LitePalParser.usePullParse(LitePalParser.java:180)
        at org.litepal.parser.LitePalParser.parseLitePalConfiguration(LitePalParser.java:102)
        at org.litepal.parser.LitePalAttr.getInstance(LitePalAttr.java:91)
        at org.litepal.tablemanager.Connector.buildConnection(Connector.java:98)
        at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:57)
        at org.litepal.tablemanager.Connector.getDatabase(Connector.java:81)
        at com.wbm.lib_base_service.application.MyApp.onCreate(MyApp.java:63)
        at com.wbm.app.application.MyApplication.onCreate(MyApplication.java:28)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5421)
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1547) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6137) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
2018-11-26 16:50:37.019 1135-1229/? W/ActivityManager:   Force finishing activity com.wbm.app.activity/.GuideActivity

**Comment by FJCDrome** [comment]
![image](https://user-images.githubusercontent.com/22695744/49002863-aed1a580-f19b-11e8-9696-89f6464fdf04.png)

**Comment by FJCDrome** [comment]
顺便2楼我在混淆的正式包里打印了一下litepal.xml的内容,看上去没问题,但是接下来就报错了,看了下代码是解析litepal.xml的问题. 不过这个代码在不混淆/没有引入我1楼说的某个jar包之前是正常的,很神奇

**Comment by guolindev** [comment]
litepal cache住的这种异常叫已知异常，就是提醒你什么地方出了问题让你自己去查的。如果litepal什么异常都不cache，崩了就直接崩了，那你想查问题还得去看litepal的源码，而且这个问题可能还不是给你看的，而是给我看的。毕竟不是每个人都要懂litepal的源码才能使用litepal。

**Comment by FJCDrome** [comment]
好像我并没有说不要cache么,作者看了我写的文字么,毕竟是花时间找到这个项目来写的. cache异常没问题,但是我个人觉得如果把原始的异常打印出来或许会有助于使用的人解决一些问题. 反正只是提点建议罢了,如果这些cache住的异常只能给这个项目的作者看么,我也没话说
