### ISSUE TITLE
混淆后报错 can not parse the litepal.xml, check if it's in correct format

### ISSUE THREAD

**Issue by alidili** [LitePalFramework/LitePal#491]
代码混淆后，报如下错误，如果不混淆的话是正常的：
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.forclass.fcagent/net.forclass.fcagent.ui.activity.SaveActivity}: org.litepal.exceptions.ParseConfigurationFileException: can not parse the litepal.xml, check if it's in correct format
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3194)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: org.litepal.exceptions.ParseConfigurationFileException: can not parse the litepal.xml, check if it's in correct format
	at org.litepal.parser.LitePalParser.usePullParse(Unknown Source:158)
	at org.litepal.parser.LitePalParser.parseLitePalConfiguration(Unknown Source:13)
	at org.litepal.parser.LitePalAttr.loadLitePalXMLConfiguration(Unknown Source:6)
	at org.litepal.parser.LitePalAttr.getInstance(Unknown Source:18)
	at org.litepal.tablemanager.Connector.buildConnection(Unknown Source:0)
	at org.litepal.tablemanager.Connector.getWritableDatabase(Unknown Source:3)
	at org.litepal.tablemanager.Connector.getDatabase(Unknown Source:0)
	at org.litepal.FluentQuery.find(Unknown Source:5)
	at org.litepal.FluentQuery.find(Unknown Source:1)
	at net.forclass.fcagent.database.DBUtils.getModuleInfoList(Unknown Source:21)
	at net.forclass.fcagent.ui.activity.SaveActivity.initData(Unknown Source:210)
	at net.forclass.fcagent.ui.activity.SaveActivity.onCreate(Unknown Source:12)
	at android.app.Activity.performCreate(Activity.java:7372)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
	... 9 more
org.litepal.exceptions.ParseConfigurationFileException: can not parse the litepal.xml, check if it's in correct format
	at org.litepal.parser.LitePalParser.usePullParse(Unknown Source:158)
	at org.litepal.parser.LitePalParser.parseLitePalConfiguration(Unknown Source:13)
	at org.litepal.parser.LitePalAttr.loadLitePalXMLConfiguration(Unknown Source:6)
	at org.litepal.parser.LitePalAttr.getInstance(Unknown Source:18)
	at org.litepal.tablemanager.Connector.buildConnection(Unknown Source:0)
	at org.litepal.tablemanager.Connector.getWritableDatabase(Unknown Source:3)
	at org.litepal.tablemanager.Connector.getDatabase(Unknown Source:0)
	at org.litepal.FluentQuery.find(Unknown Source:5)
	at org.litepal.FluentQuery.find(Unknown Source:1)
	at net.forclass.fcagent.database.DBUtils.getModuleInfoList(Unknown Source:21)
	at net.forclass.fcagent.ui.activity.SaveActivity.initData(Unknown Source:210)
	at net.forclass.fcagent.ui.activity.SaveActivity.onCreate(Unknown Source:12)
	at android.app.Activity.performCreate(Activity.java:7372)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7425)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

混淆配置：

```
# 保持litepal不被混淆
-keep class org.litepal.** { *; }
-keep class * extends org.litepal.crud.DataSupport { *; }
-keep class * extends org.litepal.crud.LitePalSupport { *; }
```

buildTypes：

```
buildTypes {
	release {
		// 开启混淆
		minifyEnabled true
		// 忽略文件
		shrinkResources true
		// 混淆配置文件
		proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
		// 签名配置
		signingConfig signingConfigs.signConfig
	}
}
```

litepal.xml放在了src/main/assets/目录下：

```
<?xml version="1.0" encoding="utf-8"?>
<litepal>
    <!-- 数据库名称 -->
    <dbname value="fcnote" />

    <!-- 数据库版本 -->
    <version value="1" />

    <list>
        <mapping class="net.forclass.fcagent.database.ModuleInfo" />
        <mapping class="net.forclass.fcagent.database.CategoryInfo" />
        <mapping class="net.forclass.fcagent.database.NoteInfo" />
    </list>
</litepal>
```

**Comment by guolindev** [comment]
sorry，这个问题我真没法帮你定位，之前也有一个跟我说遇到这个问题的，最后他了好几天查下来是和某个第三方库冲突，那个第三方库把PullParse解析库给屏蔽了，因为我也无法了解你的项目引入了哪些第三方库，所以这个问题我无法预判出来原因。

但是我这边给你个定位问题的思路吧，首先请不用怀疑是litepal的bug，如果不相信的话，你可以新建一个Demo工程，然后用Demo工程集成litepal打一个release包，看看能不能正常工作，我可以向你保证一定是能正常工作的。

然后至于和哪个第三方库产生了冲突，这个只能用排除法才好判断，你先自己有个大概的猜测，然后把怀疑的这个库注释掉，看看再打包是不是就ok了，如果还不行那就说明不是这个库，再去注释另外一个库，虽然有点笨，但确实是解决问题的一种好方法。

**Comment by alidili** [comment]
已经解决，谢谢，引用的第三库中有一个使用了PullParse，包名为org.xmlpull.v1，在混淆配置中忽略就可以了
-keep class org.**{ *; }
