### ISSUE TITLE
出现报错：android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed.

### ISSUE THREAD

**Issue by ShowerBoy** [LitePalFramework/LitePal#499]
版本是1.6.0，数据库操作只用到DataSupport.find()，程序运行一段时候后就会报这个错，不知道什么原因...

2019-01-17 11:29:10.382 19151-24591/com.annie.annieforchild E/--Main--: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
        at android.database.CursorWindow.<init>(CursorWindow.java:108)
        at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
        at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
        at com.yanzhenjie.nohttp.cookie.CookieEntityDao.getList(CookieEntityDao.java:80)
        at com.yanzhenjie.nohttp.db.BaseDao.getList(BaseDao.java:210)
        at com.yanzhenjie.nohttp.cookie.DBCookieStore.get(DBCookieStore.java:147)
        at java.net.CookieManager.get(CookieManager.java:213)
        at com.yanzhenjie.nohttp.Headers.addCookie(Headers.java:292)
        at com.yanzhenjie.nohttp.HttpConnection.createNetwork(HttpConnection.java:166)
        at com.yanzhenjie.nohttp.HttpConnection.createConnectionAndWriteData(HttpConnection.java:120)
        at com.yanzhenjie.nohttp.HttpConnection.getConnection(HttpConnection.java:75)
        at com.yanzhenjie.nohttp.rest.RequestHandler.getHttpProtocol(RequestHandler.java:176)
        at com.yanzhenjie.nohttp.rest.RequestHandler.requestCacheOrNetwork(RequestHandler.java:138)
        at com.yanzhenjie.nohttp.rest.RequestHandler.handle(RequestHandler.java:73)
        at com.yanzhenjie.nohttp.rest.SyncRequestExecutor.execute(SyncRequestExecutor.java:46)
        at com.yanzhenjie.nohttp.rest.RequestDispatcher.run(RequestDispatcher.java:88)

**Comment by guolindev** [comment]
从错误信息上来看，没有看到和LitePal相关的堆栈。

可以参考这个issue中的回复 https://github.com/LitePalFramework/LitePal/issues/576
