### ISSUE TITLE
查询数据报错

### ISSUE THREAD

**Issue by xf222zt** [LitePalFramework/LitePal#508]
我之前使用Litepal2.0没出现什么问题，但是在华为上就报了如下问题：
 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference 
看issue有类似的问题，说升级到3.0，但是问题依旧出现。

**Comment by guolindev** [comment]
有具体的堆栈信息发出来看一下吗，要不然我也没法判断是在哪个类哪一行出的错误。

**Comment by crzaycat** [comment]
org.litepal.exceptions.LitePalSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
        at org.litepal.crud.DataHandler.query(DataHandler.java:154)
        at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
        at org.litepal.FluentQuery.find(FluentQuery.java:234)
        at org.litepal.FluentQuery.find(FluentQuery.java:195)


升级到3.0依然存在此问题

**Comment by guolindev** [comment]
不好意思，这个问题隔得有点太久了，如果有实体类定义能发出来看一下吗？

**Comment by guolindev** [comment]
由于是重复问题且过去久远，我先将这个问题关闭，后续可以关注这个issue的解决情况 https://github.com/LitePalFramework/LitePal/issues/561
