### ISSUE TITLE
findAll 报错

### ISSUE THREAD

**Issue by GitHuborz** [LitePalFramework/LitePal#521]
01-01 23:04:35.396  8157  8157 E SQLiteDatabase: android.database.sqlite.SQLiteException: table table_schema has no column named name (code 1): , while compiling: INSERT INTO table_schema(name,type) VALUES (?,?)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1472)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at org.litepal.tablemanager.AssociationCreator.giveTableSchemaACopy(AssociationCreator.java:203)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at org.litepal.tablemanager.Creator.createOrUpgradeTable(Creator.java:55)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at org.litepal.tablemanager.Creator.createOrUpgradeTable(Creator.java:49)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at org.litepal.tablemanager.Generator.create(Generator.java:171)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at org.litepal.tablemanager.Generator.create(Generator.java:209)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at org.litepal.tablemanager.LitePalOpenHelper.onCreate(LitePalOpenHelper.java:83)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:64)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at org.litepal.tablemanager.Connector.getDatabase(Connector.java:87)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at org.litepal.LitePal.findAll(LitePal.java:1113)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at org.litepal.LitePal.findAll(LitePal.java:1079)
01-01 23:04:35.396  8157  8157 E SQLiteDatabase:        at sw.iot.droid.xwlauncher3.XWLauncher.refreshUi(XWLauncher.java:323)

可是我都没用 table_schema 这个表，我查的是 List<XWContactBean> beanList = LitePal.findAll(XWContactBean.class);

这个 XWContactBean 表。。。

**Comment by GitHuborz** [comment]
@guolindev 

郭婶婶

**Comment by GitHuborz** [comment]
哈哈哈，谢谢郭婶婶在群里解答。给了思路


我是在Android.mk 中引用的jar 库文件

关了混淆就好了。

哈哈哈
