### ISSUE TITLE
SQLiteException

### ISSUE THREAD

**Issue by hearsilent** [LitePalFramework/LitePal#530]
```
Fatal Exception: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/user/0/com.test.sample/databases/database.db' to 'zh_TW'.
       at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:393)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:723)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:310)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
       at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:63)
       at org.litepal.tablemanager.Connector.getDatabase(Connector.java:75)
       at org.litepal.FluentQuery.count(FluentQuery.java:495)
       at org.litepal.Operator.count(Operator.java:362)
       at org.litepal.Operator.count(Operator.java:327)
       at org.litepal.LitePal.count(LitePal.java:211)
```

It's can be fix by `SQLiteDatabase.NO_LOCALIZED_COLLATORS` with `openDatabase`.
But SQLiteOpenHelper doesn't support this. 
Maybe should write custom SQLiteOpenHelper to fix it.

**Comment by ooftf** [comment]
同问

**Comment by ooftf** [comment]
这个问题我这边已经修复了，不知道是不是和你是同样的问题引起的，我这边是由于多线程引起的

**Comment by hearsilent** [comment]
@ooftf 我不是很確定，但發生機率很低
後來我暫時解法是給 LitePal 的 context 都是用跟 Database 的語系同樣的

**Comment by ooftf** [comment]
> @ooftf 我不是很確定，但發生機率很低
> 後來我暫時解法是給 LitePal 的 context 都是用跟 Database 的語系同樣的

如果你的应用存在多进程，并且你有部分数据库操作是在application中，那就有可能导致这个问题

**Comment by guolindev** [comment]
这个问题看上去更像是SQLite报出的错误，而非LitePal报出的错误。

由于问题已经过去很久，不知是否还有人继续关注，我先close掉，如果还有疑问的话请重新打开。

**Comment by ShengjieGeng** [comment]
![image](https://user-images.githubusercontent.com/18364968/87926034-b43bdc00-cab3-11ea-870c-0e993d6d50e8.png)
最近我们设备（全志A33的板子，Android5.1的系统）出现了好多次这个异常，有大神们遇到过吗
