### ISSUE TITLE
实体类实现Parcelable后，查询包反射空异常

### ISSUE THREAD

**Issue by zouqingliang** [LitePalFramework/LitePal#554]
Caused by: org.litepal.exceptions.LitePalSupportException: Attempt to invoke virtual method 'java.lang.Class[] java.lang.reflect.Constructor.getParameterTypes()' on a null object reference
        at org.litepal.crud.DataHandler.query(DataHandler.java:154)
        at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
        at org.litepal.FluentQuery.find(FluentQuery.java:234)
        at org.litepal.FluentQuery.find(FluentQuery.java:195)

**Comment by zouqingliang** [comment]
自己发现问题了，没有空构造方法
