### ISSUE TITLE
改变Boolean类型字段为false时，调用updateAll方法闪退

### ISSUE THREAD

**Issue by nespjin** [LitePalFramework/LitePal#566]
错误信息：
```
org.litepal.exceptions.LitePalSupportException: method android.content.ContentValues.put argument 2 has type java.lang.Boolean, got java.lang.Integer
        at org.litepal.crud.LitePalSupport.updateAll(LitePalSupport.java:283)
```

```
     Caused by: java.lang.IllegalArgumentException: method android.content.ContentValues.put argument 2 has type java.lang.Boolean, got java.lang.Integer
        at java.lang.reflect.Method.invoke(Native Method)
        at org.litepal.crud.DynamicExecutor.send(DynamicExecutor.java:73)
        at org.litepal.crud.UpdateHandler.updateGenericTables(UpdateHandler.java:366)
        at org.litepal.crud.UpdateHandler.onUpdateAll(UpdateHandler.java:150)
        at org.litepal.crud.LitePalSupport.updateAll(LitePalSupport.java:279)

```

我写了一个测试先find数据库里面的值，然后设置Boolean类型为true，再save是正常的，然而在项目中同样的操作却报错了，版本是3.0.0，试过setToDefault也是无用，望解答，谢谢啦！

**Comment by xiazunyang** [comment]
使用1和0代替true和false

**Comment by ns-jin** [comment]
> 使用1和0代替true和false

实体类中的布尔型要改成整型吗？那太不方便了吧，能不能内部转换一下

**Comment by guolindev** [comment]
有具体的代码吗？仅从错误上来看，好像是方面期望接收Boolean，却实际得到了Integer。

**Comment by guolindev** [comment]
由于问题久远，我先将此问题关闭，如果后续还有人继续关注这个问题，请再重新打开。
