### ISSUE TITLE
Android 10.0 adaptation problems

### ISSUE THREAD

**Issue by chenyinuan88** [LitePalFramework/LitePal#582]
When my project run on Build.VERSION_CODES.Q，I finded this problem:
E/SQLiteDatabase: Failed to open database '/storage/emulated/0/backups/system/.confd'.
 android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:915)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:895)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:759)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:748)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:374)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)

wait for your processing scheme,thank you!

**Comment by guolindev** [comment]
I didn't see any stack trace related with LitePal. So I didn't know where to start.

Maybe you can check this question on Stackoverflow https://stackoverflow.com/questions/46974359/error-failed-to-open-database-storage-emulated-0-database-db-sqlite

**Comment by zhaoxiuyu** [comment]
我也出现了这个问题，请问你是怎么解决的 @chenyinuan88  
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (Sqlite code 14 SQLITE_CANTOPEN): Could not open database, (OS error - 2:No such file or directory)

**Comment by sdgSnow** [comment]
+1，我遇到了跟你一样的问题，而且我用的3.0.0版本，在Android10会报错，Android7没问题
