### ISSUE TITLE
一查询数据库就出现anr，被锁定

### ISSUE THREAD

**Issue by wilson123** [LitePalFramework/LitePal#592]
下载litepal源码到本地，并使用sqlcipher（'net.zetetic:android-database-sqlcipher:4.2.0'）对数据库文件进行加密，出现特定一份数据只要去查询数据库就提示被锁定，导致anr
  at org.litepal.FluentQuery.find(FluentQuery.java:223)
  - waiting to lock <0x031cc3c9> (a java.lang.Class<org.litepal.crud.LitePalSupport>) held by thread 102
  at org.litepal.FluentQuery.find(FluentQuery.java:195)
  at com.leelen.luxdomo.home.dao.LogicServerDao.getLogicServerListByTypeListWithoutIconId(LogicServerDao.java:450)
  at com.leelen.luxdomo.common.model.DeviceModel.getLogicServerListByLogicTypeListWithoutIconId(DeviceModel.java:237)
  at com.leelen.luxdomo.safe.presenter.SensorPresenter.getLogicList(SensorPresenter.java:69)
  - locked <0x07a4682b> (a com.leelen.luxdomo.safe.presenter.SensorPresenter)
  at com.leelen.luxdomo.safe.SensorFragment.initViews(SensorFragment.java:143)

**Comment by wilson123** [comment]
"main" prio=5 tid=1 Blocked
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x73e37560 self=0xeb04b000
  | sysTid=19378 nice=-10 cgrp=default sched=0/0 handle=0xef3154a8
  | state=S schedstat=( 3449998463 168155721 1861 ) utm=314 stm=30 core=4 HZ=100
  | stack=0xff463000-0xff465000 stackSize=8MB
  | held mutexes=
  at org.litepal.FluentQuery.find(FluentQuery.java:223)
  - waiting to lock <0x01d5d418> (a java.lang.Class<org.litepal.crud.LitePalSupport>) held by thread 103
  at org.litepal.FluentQuery.find(FluentQuery.java:195)
  at com.leelen.luxdomo.more.dao.AccountDao.getAllAccountList(AccountDao.java:136)
  at com.leelen.luxdomo.more.familymember.model.FamilyMemberModel.getAllAccountList(FamilyMemberModel.java:25)
  at com.leelen.luxdomo.more.familymember.presenter.FamilyMemberPresenter.getAllAccountList(FamilyMemberPresenter.java:39)

**Comment by wilson123** [comment]
at net.sqlcipher.database.SQLiteProgram.native_bind_string(Native method)
  at net.sqlcipher.database.SQLiteProgram.bindString(SQLiteProgram.java:262)
  at net.sqlcipher.database.SQLiteQuery.bindString(SQLiteQuery.java:192)
  at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:66)
  at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2012)
  at net.sqlcipher.database.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1795)
  at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:1747)
  at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:1879)
  at org.litepal.crud.DataHandler.query(DataHandler.java:133)
  at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
  at org.litepal.FluentQuery.find(FluentQuery.java:234)
  - locked <0x0904598a> (a java.lang.Class<org.litepal.crud.LitePalSupport>)
  at org.litepal.FluentQuery.findFirst(FluentQuery.java:316)
  - locked <0x0904598a> (a java.lang.Class<org.litepal.crud.LitePalSupport>)
  at org.litepal.FluentQuery.findFirst(FluentQuery.java:287)
  at com.leelen.luxdomo.more.dao.RoomDao.getRoomByRoomId(RoomDao.java:135)

**Comment by wilson123** [comment]
at net.sqlcipher.database.SQLiteProgram.native_bind_string(Native method)
  at net.sqlcipher.database.SQLiteProgram.bindString(SQLiteProgram.java:262)
  at net.sqlcipher.database.SQLiteQuery.bindString(SQLiteQuery.java:192)
  at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:66)
  at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2012)
  at net.sqlcipher.database.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1795)
  at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:1747)
  at net.sqlcipher.database.SQLiteDatabase.query(SQLiteDatabase.java:1879)
  at org.litepal.crud.DataHandler.query(DataHandler.java:133)
  at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
  at org.litepal.FluentQuery.find(FluentQuery.java:234)
  - locked <0x0904598a> (a java.lang.Class<org.litepal.crud.LitePalSupport>)
  at org.litepal.FluentQuery.findFirst(FluentQuery.java:316)
  - locked <0x0904598a> (a java.lang.Class<org.litepal.crud.LitePalSupport>)
  at org.litepal.FluentQuery.findFirst(FluentQuery.java:287)
  at com.leelen.luxdomo.more.dao.RoomDao.getRoomByRoomId(RoomDao.java:135)
