### ISSUE TITLE
kotlin libcore.reflect.WildcardTypeImpl cannot be cast to java.lang.Class

### ISSUE THREAD

**Issue by LJFDBXJ** [LitePalFramework/LitePal#610]
使用语言 
kotlin

异常内容 
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.leadjoy.video/com.leadjoy.video.main.ui.study.StudyActivity}: org.litepal.exceptions.LitePalSupportException: libcore.reflect.WildcardTypeImpl cannot be cast to java.lang.Class
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3760)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3939)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8147)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: org.litepal.exceptions.LitePalSupportException: libcore.reflect.WildcardTypeImpl cannot be cast to java.lang.Class
        at org.litepal.crud.DataHandler.query(DataHandler.java:154)
        at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159)
        at org.litepal.FluentQuery.find(FluentQuery.java:234)
        at org.litepal.FluentQuery.find(FluentQuery.java:195)
        at com.leadjoy.video.main.db.DbHelper.getStudyAlbums(DbHelper.kt:581)
        at com.leadjoy.video.main.ui.study.StudyActivity.onCreate(StudyActivity.kt:173)
        at android.app.Activity.performCreate(Activity.java:8066)
        at android.app.Activity.performCreate(Activity.java:8054)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3733)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3939) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8147) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 
     Caused by: java.lang.ClassCastException: libcore.reflect.WildcardTypeImpl cannot be cast to java.lang.Class
        at org.litepal.LitePalBase.getGenericTypeClass(LitePalBase.java:316)
        at org.litepal.LitePalBase.getGenericTypeName(LitePalBase.java:677)
        at org.litepal.LitePalBase.recursiveSupportedGenericFields(LitePalBase.java:359)
        at org.litepal.LitePalBase.recursiveSupportedGenericFields(LitePalBase.java:366)
        at org.litepal.LitePalBase.getSupportedGenericFields(LitePalBase.java:221)
        at org.litepal.crud.DataHandler.query(DataHandler.java:130)
        at org.litepal.crud.QueryHandler.onFind(QueryHandler.java:159) 
        at org.litepal.FluentQuery.find(FluentQuery.java:234) 
        at org.litepal.FluentQuery.find(FluentQuery.java:195) 
        at com.leadjoy.video.main.db.DbHelper.getStudyAlbums(DbHelper.kt:581) 
        at com.leadjoy.video.main.ui.study.StudyActivity.onCreate(StudyActivity.kt:173) 
        at android.app.Activity.performCreate(Activity.java:8066) 
        at android.app.Activity.performCreate(Activity.java:8054) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3733) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3939) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2373) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:213) 
        at android.app.ActivityThread.main(ActivityThread.java:8147) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) 

具体 走到 源码异常位置
    /**
     * Get the generic type class of List or Set. If there's no generic type of
     * List or Set return null.
     *
     * @param field
     *            A generic type field.
     * @return The generic type of List or Set.
     */
    protected Class<?> getGenericTypeClass(Field field) {
        Type genericType = field.getGenericType();
        if (genericType != null) {
            if (genericType instanceof ParameterizedType) {
                ParameterizedType parameterizedType = (ParameterizedType) genericType;
                return (Class<?>) parameterizedType.getActualTypeArguments()[0];//这一句抛出异常，libcore.reflect.WildcardTypeImpl cannot be cast to java.lang.Class
            }
        }
        return null;
    }

查询语句
    val studyAlbums: List<StudyAlbumEntity>
        get() = LitePal.order("update_time asc").find(StudyAlbumEntity::class.java)

实体子类
class StudyAlbumEntity : DataCatEntity() {
    var album_id = 0
    @Column(ignore = true)
    var isCheck = 0
    var create_time: String? = null
    var update_time: String? = null

}
实体父类
open class DataCatEntity : LitePalSupport(), Serializable {
    var id = 0
    @Column(ignore = true)
    var sousuo: String? = null
    var group_id = 0
    var title: String? = null
    var group_image: String? = null
    var group_image1: String? = null

    var group_image2: String? = null
    var is_hot = 0
    var type = 0
    var item_type: String? = null
    var vip_type = 0
    var code_number: String? = null
    var data_size: String? = null
    var data_size1: String? = null
    var data_size2: String? = null
    var apptvlis: List<AlbumInfoEntity>? = null
}

**Comment by wkk-knight** [comment]
`List<AlbumInfoEntity> `改成`MutableList<AlbumInfoEntity>`就可以了，或者用`java.util.List<AlbumInfoEntity>`用kotlin包`kotlin.collections.List`就会有问题

**Comment by LJFDBXJ** [comment]
@wkk-knight thanks 确实改为 MutableList<AlbumInfoEntity>不在报错了，非常感谢您的帮助
