### ISSUE TITLE
数据库访问冲突问题

### ISSUE THREAD

**Issue by kaku2015** [LitePalFramework/LitePal#68]
在三星galaxy note机器上使用litepal会出现如下异常

android.database.sqlite.SQLiteDatabaseLockedException: database is locked
	at android.database.sqlite.SQLiteDatabase.dbopen(SQLiteDatabase.java)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1136)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1087)
	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1174)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:859)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:228)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:157)
	at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java)
	at org.litepal.tablemanager.Connector.getDatabase(Connector.java)
        ........

其他机型暂时没有遇到同样的问题

**Comment by sinyu890807** [comment]
我有一台三星galaxy note的手机，并没有发现这个问题。从错误提示上来看，应该是你的程序在别的地方正在访问数据库，litepal也去尝试打开数据库，就失败了。如果你所有的数据库操作都是用litepal进行的话是不会出现这个问题的，因为litepal内部自己有锁，不会在并发情况下冲突的。
