### ISSUE TITLE
java.lang.IllegalArgumentException: File null/databases/baopodb.db contains a path separator

### ISSUE THREAD

**Issue by githubityu** [LitePalFramework/LitePal#92]
java.lang.IllegalArgumentException: File null/databases/baopodb.db contains a path separator
    at android.app.ContextImpl.makeFilename(ContextImpl.java:2033)
    at android.app.ContextImpl.validateFilePath(ContextImpl.java:2017)
    at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:891)
    at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:235)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164
    at org.litepal.tablemanager.Connector.getWritableDatabase(Connector.java:63)
    at org.litepal.tablemanager.Connector.getDatabase(Connector.java:95)
    at org.litepal.crud.DataSupport.saveThrows(DataSupport.java:1084)
    at org.litepal.crud.DataSupport.save(DataSupport.java:1051)
    at com.llkj.baopo.FullscreenActivity.onCreate(FullscreenActivity.java:122)
    at android.app.Activity.performCreate(Activity.java:5133)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264)
    at android.app.ActivityThread.access$600(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5136)
    at java.lang.reflect.Method.invokeNative(Native Method)

08-02 09:40:30.548 22490-22490/com.llkj.baopo W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)
_FOR_ALLOC freed 437K, 17% free 2913K/3496K, paused 37ms, total 46ms

**Comment by githubityu** [comment]
htc手机有这个问题，换个手机就正常了

**Comment by guolindev** [comment]
这个问题是因为你将数据库选择创建到了sd卡，但你的手机上没有sd卡导致的。
