### ISSUE TITLE
一对多报错 List

### ISSUE THREAD

**Issue by githubityu** [LitePalFramework/LitePal#95]
public class TestBean extends DataSupport {
    private List<String> datas = new ArrayList<String>();
    private List<TestBean2> tbs = new ArrayList<TestBean2>();

```
public List<String> getDatas() {
    return datas;
}

public void setDatas(List<String> datas) {
    this.datas = datas;
}

public List<TestBean2> getTbs() {
    return tbs;
}

public void setTbs(List<TestBean2> tbs) {
    this.tbs = tbs;
}
```

}

public class TestBean2 extends DataSupport {
    private String data;

```
public String getData() {
    return data;
}

public void setData(String data) {
    this.data = data;
}
```

}

```
  TestBean pm = new TestBean();
            List<String> datas = new ArrayList<>();
            datas.add("导爆管雷管");
            datas.add(" 数码电子雷管");
            datas.add("电雷管");
            pm.setDatas(datas);
            List<TestBean2> tb2s = new ArrayList<>();
            TestBean2 tb2 = new TestBean2();
            tb2.setData("乳化炸药");
            tb2s.add(tb2);
            pm.setTbs(tb2s);
            boolean istrue =  pm.save();
            Logger.e(istrue+"");
```

 Error inserting 
                                                              android.database.sqlite.SQLiteException: near "null": syntax error (code 1): , while compiling: INSERT INTO testbean(null) VALUES (NULL)
                                                                  at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                                  at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                                  at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                  at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                  at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                  at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
                                                                  at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
                                                                  at org.litepal.crud.SaveHandler.saving(SaveHandler.java:225)
                                                                  at org.litepal.crud.SaveHandler.doSaveAction(SaveHandler.java:184)
                                                                  at org.litepal.crud.SaveHandler.onSave(SaveHandler.java:89)
                                                                  at org.litepal.crud.DataSupport.saveThrows(DataSupport.java:1088)
                                                                  at org.litepal.crud.DataSupport.save(DataSupport.java:1051)
                                                                  at com.llkj.baopo.login.LoginActivity.onClick(LoginActivity.java:86)
                                                                  at android.view.View.performClick(View.java:5207)
                                                                  at android.view.View$PerformClick.run(View.java:21177)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5432)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:735)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)

**Comment by guolindev** [comment]
此问题1.4.1版本中已修复，升级即可解决。
